// Code generated by capnpc-go. DO NOT EDIT.

package schema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type TlsZone capnp.Struct

// TlsZone_TypeID is the unique identifier for the type TlsZone.
const TlsZone_TypeID = 0xa17bba3bf9977a36

func NewTlsZone(s *capnp.Segment) (TlsZone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TlsZone(st), err
}

func NewRootTlsZone(s *capnp.Segment) (TlsZone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TlsZone(st), err
}

func ReadRootTlsZone(msg *capnp.Message) (TlsZone, error) {
	root, err := msg.Root()
	return TlsZone(root.Struct()), err
}

func (s TlsZone) String() string {
	str, _ := text.Marshal(0xa17bba3bf9977a36, capnp.Struct(s))
	return str
}

func (s TlsZone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TlsZone) DecodeFromPtr(p capnp.Ptr) TlsZone {
	return TlsZone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TlsZone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TlsZone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TlsZone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TlsZone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TlsZone) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TlsZone) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TlsZone) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TlsZone) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TlsZone) TlsPolicy() (TlsPolicy, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TlsPolicy(p.Struct()), err
}

func (s TlsZone) HasTlsPolicy() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TlsZone) SetTlsPolicy(v TlsPolicy) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewTlsPolicy sets the tlsPolicy field to a newly
// allocated TlsPolicy struct, preferring placement in s's segment.
func (s TlsZone) NewTlsPolicy() (TlsPolicy, error) {
	ss, err := NewTlsPolicy(capnp.Struct(s).Segment())
	if err != nil {
		return TlsPolicy{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// TlsZone_List is a list of TlsZone.
type TlsZone_List = capnp.StructList[TlsZone]

// NewTlsZone creates a new list of TlsZone.
func NewTlsZone_List(s *capnp.Segment, sz int32) (TlsZone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[TlsZone](l), err
}

// TlsZone_Future is a wrapper for a TlsZone promised by a client call.
type TlsZone_Future struct{ *capnp.Future }

func (f TlsZone_Future) Struct() (TlsZone, error) {
	p, err := f.Future.Ptr()
	return TlsZone(p.Struct()), err
}
func (p TlsZone_Future) TlsPolicy() TlsPolicy_Future {
	return TlsPolicy_Future{Future: p.Future.Field(1, nil)}
}

type HttpZone capnp.Struct

// HttpZone_TypeID is the unique identifier for the type HttpZone.
const HttpZone_TypeID = 0xc69b2c0540c4d320

func NewHttpZone(s *capnp.Segment) (HttpZone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HttpZone(st), err
}

func NewRootHttpZone(s *capnp.Segment) (HttpZone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HttpZone(st), err
}

func ReadRootHttpZone(msg *capnp.Message) (HttpZone, error) {
	root, err := msg.Root()
	return HttpZone(root.Struct()), err
}

func (s HttpZone) String() string {
	str, _ := text.Marshal(0xc69b2c0540c4d320, capnp.Struct(s))
	return str
}

func (s HttpZone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HttpZone) DecodeFromPtr(p capnp.Ptr) HttpZone {
	return HttpZone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HttpZone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HttpZone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HttpZone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HttpZone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HttpZone) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HttpZone) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HttpZone) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HttpZone) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HttpZone) HttpPolicies() (HttpPolicy_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return HttpPolicy_List(p.List()), err
}

func (s HttpZone) HasHttpPolicies() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpZone) SetHttpPolicies(v HttpPolicy_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewHttpPolicies sets the httpPolicies field to a newly
// allocated HttpPolicy_List, preferring placement in s's segment.
func (s HttpZone) NewHttpPolicies(n int32) (HttpPolicy_List, error) {
	l, err := NewHttpPolicy_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return HttpPolicy_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// HttpZone_List is a list of HttpZone.
type HttpZone_List = capnp.StructList[HttpZone]

// NewHttpZone creates a new list of HttpZone.
func NewHttpZone_List(s *capnp.Segment, sz int32) (HttpZone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[HttpZone](l), err
}

// HttpZone_Future is a wrapper for a HttpZone promised by a client call.
type HttpZone_Future struct{ *capnp.Future }

func (f HttpZone_Future) Struct() (HttpZone, error) {
	p, err := f.Future.Ptr()
	return HttpZone(p.Struct()), err
}

type HttpPolicy capnp.Struct
type HttpPolicy_Which uint16

const (
	HttpPolicy_Which_pathname HttpPolicy_Which = 0
	HttpPolicy_Which_query    HttpPolicy_Which = 1
	HttpPolicy_Which_header   HttpPolicy_Which = 2
)

func (w HttpPolicy_Which) String() string {
	const s = "pathnamequeryheader"
	switch w {
	case HttpPolicy_Which_pathname:
		return s[0:8]
	case HttpPolicy_Which_query:
		return s[8:13]
	case HttpPolicy_Which_header:
		return s[13:19]

	}
	return "HttpPolicy_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// HttpPolicy_TypeID is the unique identifier for the type HttpPolicy.
const HttpPolicy_TypeID = 0xdc3258f2d394aca0

func NewHttpPolicy(s *capnp.Segment) (HttpPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return HttpPolicy(st), err
}

func NewRootHttpPolicy(s *capnp.Segment) (HttpPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return HttpPolicy(st), err
}

func ReadRootHttpPolicy(msg *capnp.Message) (HttpPolicy, error) {
	root, err := msg.Root()
	return HttpPolicy(root.Struct()), err
}

func (s HttpPolicy) String() string {
	str, _ := text.Marshal(0xdc3258f2d394aca0, capnp.Struct(s))
	return str
}

func (s HttpPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HttpPolicy) DecodeFromPtr(p capnp.Ptr) HttpPolicy {
	return HttpPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HttpPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s HttpPolicy) Which() HttpPolicy_Which {
	return HttpPolicy_Which(capnp.Struct(s).Uint16(0))
}
func (s HttpPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HttpPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HttpPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HttpPolicy) Backend() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HttpPolicy) HasBackend() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HttpPolicy) BackendBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HttpPolicy) SetBackend(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HttpPolicy) Pathname() (Pathname, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != pathname")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Pathname(p.Struct()), err
}

func (s HttpPolicy) HasPathname() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetPathname(v Pathname) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPathname sets the pathname field to a newly
// allocated Pathname struct, preferring placement in s's segment.
func (s HttpPolicy) NewPathname() (Pathname, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewPathname(capnp.Struct(s).Segment())
	if err != nil {
		return Pathname{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) Query() (Query, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != query")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Query(p.Struct()), err
}

func (s HttpPolicy) HasQuery() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetQuery(v Query) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewQuery sets the query field to a newly
// allocated Query struct, preferring placement in s's segment.
func (s HttpPolicy) NewQuery() (Query, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewQuery(capnp.Struct(s).Segment())
	if err != nil {
		return Query{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) Header() (Header, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != header")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Header(p.Struct()), err
}

func (s HttpPolicy) HasHeader() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetHeader(v Header) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewHeader sets the header field to a newly
// allocated Header struct, preferring placement in s's segment.
func (s HttpPolicy) NewHeader() (Header, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewHeader(capnp.Struct(s).Segment())
	if err != nil {
		return Header{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// HttpPolicy_List is a list of HttpPolicy.
type HttpPolicy_List = capnp.StructList[HttpPolicy]

// NewHttpPolicy creates a new list of HttpPolicy.
func NewHttpPolicy_List(s *capnp.Segment, sz int32) (HttpPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[HttpPolicy](l), err
}

// HttpPolicy_Future is a wrapper for a HttpPolicy promised by a client call.
type HttpPolicy_Future struct{ *capnp.Future }

func (f HttpPolicy_Future) Struct() (HttpPolicy, error) {
	p, err := f.Future.Ptr()
	return HttpPolicy(p.Struct()), err
}
func (p HttpPolicy_Future) Pathname() Pathname_Future {
	return Pathname_Future{Future: p.Future.Field(1, nil)}
}
func (p HttpPolicy_Future) Query() Query_Future {
	return Query_Future{Future: p.Future.Field(1, nil)}
}
func (p HttpPolicy_Future) Header() Header_Future {
	return Header_Future{Future: p.Future.Field(1, nil)}
}

type Pathname capnp.Struct
type Pathname_Which uint16

const (
	Pathname_Which_exact  Pathname_Which = 0
	Pathname_Which_prefix Pathname_Which = 1
	Pathname_Which_regex  Pathname_Which = 2
)

func (w Pathname_Which) String() string {
	const s = "exactprefixregex"
	switch w {
	case Pathname_Which_exact:
		return s[0:5]
	case Pathname_Which_prefix:
		return s[5:11]
	case Pathname_Which_regex:
		return s[11:16]

	}
	return "Pathname_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Pathname_TypeID is the unique identifier for the type Pathname.
const Pathname_TypeID = 0xa52079c444398c22

func NewPathname(s *capnp.Segment) (Pathname, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Pathname(st), err
}

func NewRootPathname(s *capnp.Segment) (Pathname, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Pathname(st), err
}

func ReadRootPathname(msg *capnp.Message) (Pathname, error) {
	root, err := msg.Root()
	return Pathname(root.Struct()), err
}

func (s Pathname) String() string {
	str, _ := text.Marshal(0xa52079c444398c22, capnp.Struct(s))
	return str
}

func (s Pathname) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Pathname) DecodeFromPtr(p capnp.Ptr) Pathname {
	return Pathname(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Pathname) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Pathname) Which() Pathname_Which {
	return Pathname_Which(capnp.Struct(s).Uint16(2))
}
func (s Pathname) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Pathname) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Pathname) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Pathname) Kind() Pathname_Kind {
	return Pathname_Kind(capnp.Struct(s).Uint16(0))
}

func (s Pathname) SetKind(v Pathname_Kind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Pathname) Exact() (string, error) {
	if capnp.Struct(s).Uint16(2) != 0 {
		panic("Which() != exact")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasExact() bool {
	if capnp.Struct(s).Uint16(2) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) ExactBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetExact(v string) error {
	capnp.Struct(s).SetUint16(2, 0)
	return capnp.Struct(s).SetText(0, v)
}

func (s Pathname) Prefix() (string, error) {
	if capnp.Struct(s).Uint16(2) != 1 {
		panic("Which() != prefix")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasPrefix() bool {
	if capnp.Struct(s).Uint16(2) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) PrefixBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetPrefix(v string) error {
	capnp.Struct(s).SetUint16(2, 1)
	return capnp.Struct(s).SetText(0, v)
}

func (s Pathname) Regex() (string, error) {
	if capnp.Struct(s).Uint16(2) != 2 {
		panic("Which() != regex")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasRegex() bool {
	if capnp.Struct(s).Uint16(2) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) RegexBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetRegex(v string) error {
	capnp.Struct(s).SetUint16(2, 2)
	return capnp.Struct(s).SetText(0, v)
}

// Pathname_List is a list of Pathname.
type Pathname_List = capnp.StructList[Pathname]

// NewPathname creates a new list of Pathname.
func NewPathname_List(s *capnp.Segment, sz int32) (Pathname_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Pathname](l), err
}

// Pathname_Future is a wrapper for a Pathname promised by a client call.
type Pathname_Future struct{ *capnp.Future }

func (f Pathname_Future) Struct() (Pathname, error) {
	p, err := f.Future.Ptr()
	return Pathname(p.Struct()), err
}

type Pathname_Kind uint16

// Pathname_Kind_TypeID is the unique identifier for the type Pathname_Kind.
const Pathname_Kind_TypeID = 0xc884830b9e9c9ee6

// Values of Pathname_Kind.
const (
	Pathname_Kind_exact  Pathname_Kind = 0
	Pathname_Kind_prefix Pathname_Kind = 1
	Pathname_Kind_regex  Pathname_Kind = 2
)

// String returns the enum's constant name.
func (c Pathname_Kind) String() string {
	switch c {
	case Pathname_Kind_exact:
		return "exact"
	case Pathname_Kind_prefix:
		return "prefix"
	case Pathname_Kind_regex:
		return "regex"

	default:
		return ""
	}
}

// Pathname_KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Pathname_KindFromString(c string) Pathname_Kind {
	switch c {
	case "exact":
		return Pathname_Kind_exact
	case "prefix":
		return Pathname_Kind_prefix
	case "regex":
		return Pathname_Kind_regex

	default:
		return 0
	}
}

type Pathname_Kind_List = capnp.EnumList[Pathname_Kind]

func NewPathname_Kind_List(s *capnp.Segment, sz int32) (Pathname_Kind_List, error) {
	return capnp.NewEnumList[Pathname_Kind](s, sz)
}

type Query capnp.Struct

// Query_TypeID is the unique identifier for the type Query.
const Query_TypeID = 0xc59c8ee4dce11545

func NewQuery(s *capnp.Segment) (Query, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Query(st), err
}

func NewRootQuery(s *capnp.Segment) (Query, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Query(st), err
}

func ReadRootQuery(msg *capnp.Message) (Query, error) {
	root, err := msg.Root()
	return Query(root.Struct()), err
}

func (s Query) String() string {
	str, _ := text.Marshal(0xc59c8ee4dce11545, capnp.Struct(s))
	return str
}

func (s Query) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Query) DecodeFromPtr(p capnp.Ptr) Query {
	return Query(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Query) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Query) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Query) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Query) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Query) Items() (KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValue_List(p.List()), err
}

func (s Query) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Query) SetItems(v KeyValue_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated KeyValue_List, preferring placement in s's segment.
func (s Query) NewItems(n int32) (KeyValue_List, error) {
	l, err := NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Query_List is a list of Query.
type Query_List = capnp.StructList[Query]

// NewQuery creates a new list of Query.
func NewQuery_List(s *capnp.Segment, sz int32) (Query_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Query](l), err
}

// Query_Future is a wrapper for a Query promised by a client call.
type Query_Future struct{ *capnp.Future }

func (f Query_Future) Struct() (Query, error) {
	p, err := f.Future.Ptr()
	return Query(p.Struct()), err
}

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0x8ab888cb3bbd007f

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0x8ab888cb3bbd007f, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Items() (KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValue_List(p.List()), err
}

func (s Header) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) SetItems(v KeyValue_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated KeyValue_List, preferring placement in s's segment.
func (s Header) NewItems(n int32) (KeyValue_List, error) {
	l, err := NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type KeyValue capnp.Struct

// KeyValue_TypeID is the unique identifier for the type KeyValue.
const KeyValue_TypeID = 0xdd80c62b5abfc321

func NewKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func NewRootKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func ReadRootKeyValue(msg *capnp.Message) (KeyValue, error) {
	root, err := msg.Root()
	return KeyValue(root.Struct()), err
}

func (s KeyValue) String() string {
	str, _ := text.Marshal(0xdd80c62b5abfc321, capnp.Struct(s))
	return str
}

func (s KeyValue) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (KeyValue) DecodeFromPtr(p capnp.Ptr) KeyValue {
	return KeyValue(capnp.Struct{}.DecodeFromPtr(p))
}

func (s KeyValue) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s KeyValue) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s KeyValue) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s KeyValue) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s KeyValue) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s KeyValue) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s KeyValue) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s KeyValue) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s KeyValue) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s KeyValue) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s KeyValue) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s KeyValue) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// KeyValue_List is a list of KeyValue.
type KeyValue_List = capnp.StructList[KeyValue]

// NewKeyValue creates a new list of KeyValue.
func NewKeyValue_List(s *capnp.Segment, sz int32) (KeyValue_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[KeyValue](l), err
}

// KeyValue_Future is a wrapper for a KeyValue promised by a client call.
type KeyValue_Future struct{ *capnp.Future }

func (f KeyValue_Future) Struct() (KeyValue, error) {
	p, err := f.Future.Ptr()
	return KeyValue(p.Struct()), err
}

type BackendRef capnp.Struct

// BackendRef_TypeID is the unique identifier for the type BackendRef.
const BackendRef_TypeID = 0x9940e34bf23385a8

func NewBackendRef(s *capnp.Segment) (BackendRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return BackendRef(st), err
}

func NewRootBackendRef(s *capnp.Segment) (BackendRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return BackendRef(st), err
}

func ReadRootBackendRef(msg *capnp.Message) (BackendRef, error) {
	root, err := msg.Root()
	return BackendRef(root.Struct()), err
}

func (s BackendRef) String() string {
	str, _ := text.Marshal(0x9940e34bf23385a8, capnp.Struct(s))
	return str
}

func (s BackendRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BackendRef) DecodeFromPtr(p capnp.Ptr) BackendRef {
	return BackendRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BackendRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BackendRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BackendRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BackendRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BackendRef) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BackendRef) HasHostname() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BackendRef) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BackendRef) SetHostname(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BackendRef) Port() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s BackendRef) SetPort(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

// BackendRef_List is a list of BackendRef.
type BackendRef_List = capnp.StructList[BackendRef]

// NewBackendRef creates a new list of BackendRef.
func NewBackendRef_List(s *capnp.Segment, sz int32) (BackendRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[BackendRef](l), err
}

// BackendRef_Future is a wrapper for a BackendRef promised by a client call.
type BackendRef_Future struct{ *capnp.Future }

func (f BackendRef_Future) Struct() (BackendRef, error) {
	p, err := f.Future.Ptr()
	return BackendRef(p.Struct()), err
}

type TlsPolicy capnp.Struct

// TlsPolicy_TypeID is the unique identifier for the type TlsPolicy.
const TlsPolicy_TypeID = 0xfba0e6ab81a6f86c

func NewTlsPolicy(s *capnp.Segment) (TlsPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return TlsPolicy(st), err
}

func NewRootTlsPolicy(s *capnp.Segment) (TlsPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return TlsPolicy(st), err
}

func ReadRootTlsPolicy(msg *capnp.Message) (TlsPolicy, error) {
	root, err := msg.Root()
	return TlsPolicy(root.Struct()), err
}

func (s TlsPolicy) String() string {
	str, _ := text.Marshal(0xfba0e6ab81a6f86c, capnp.Struct(s))
	return str
}

func (s TlsPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TlsPolicy) DecodeFromPtr(p capnp.Ptr) TlsPolicy {
	return TlsPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TlsPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TlsPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TlsPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TlsPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TlsPolicy) Sni() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TlsPolicy) HasSni() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TlsPolicy) SniBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetSni(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TlsPolicy) CertPem() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TlsPolicy) HasCertPem() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TlsPolicy) CertPemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetCertPem(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TlsPolicy) KeyPem() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TlsPolicy) HasKeyPem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TlsPolicy) KeyPemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetKeyPem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TlsPolicy) Kind() TlsPolicy_Kind {
	return TlsPolicy_Kind(capnp.Struct(s).Uint16(0))
}

func (s TlsPolicy) SetKind(v TlsPolicy_Kind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s TlsPolicy) BackendRef() (BackendRef, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return BackendRef(p.Struct()), err
}

func (s TlsPolicy) HasBackendRef() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TlsPolicy) SetBackendRef(v BackendRef) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewBackendRef sets the backendRef field to a newly
// allocated BackendRef struct, preferring placement in s's segment.
func (s TlsPolicy) NewBackendRef() (BackendRef, error) {
	ss, err := NewBackendRef(capnp.Struct(s).Segment())
	if err != nil {
		return BackendRef{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// TlsPolicy_List is a list of TlsPolicy.
type TlsPolicy_List = capnp.StructList[TlsPolicy]

// NewTlsPolicy creates a new list of TlsPolicy.
func NewTlsPolicy_List(s *capnp.Segment, sz int32) (TlsPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[TlsPolicy](l), err
}

// TlsPolicy_Future is a wrapper for a TlsPolicy promised by a client call.
type TlsPolicy_Future struct{ *capnp.Future }

func (f TlsPolicy_Future) Struct() (TlsPolicy, error) {
	p, err := f.Future.Ptr()
	return TlsPolicy(p.Struct()), err
}
func (p TlsPolicy_Future) BackendRef() BackendRef_Future {
	return BackendRef_Future{Future: p.Future.Field(3, nil)}
}

type TlsPolicy_Kind uint16

// TlsPolicy_Kind_TypeID is the unique identifier for the type TlsPolicy_Kind.
const TlsPolicy_Kind_TypeID = 0x88ddbc04e9781b3b

// Values of TlsPolicy_Kind.
const (
	TlsPolicy_Kind_tlsPassthrough TlsPolicy_Kind = 0
	TlsPolicy_Kind_tlsTerminate   TlsPolicy_Kind = 1
	TlsPolicy_Kind_https          TlsPolicy_Kind = 2
)

// String returns the enum's constant name.
func (c TlsPolicy_Kind) String() string {
	switch c {
	case TlsPolicy_Kind_tlsPassthrough:
		return "tlsPassthrough"
	case TlsPolicy_Kind_tlsTerminate:
		return "tlsTerminate"
	case TlsPolicy_Kind_https:
		return "https"

	default:
		return ""
	}
}

// TlsPolicy_KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TlsPolicy_KindFromString(c string) TlsPolicy_Kind {
	switch c {
	case "tlsPassthrough":
		return TlsPolicy_Kind_tlsPassthrough
	case "tlsTerminate":
		return TlsPolicy_Kind_tlsTerminate
	case "https":
		return TlsPolicy_Kind_https

	default:
		return 0
	}
}

type TlsPolicy_Kind_List = capnp.EnumList[TlsPolicy_Kind]

func NewTlsPolicy_Kind_List(s *capnp.Segment, sz int32) (TlsPolicy_Kind_List, error) {
	return capnp.NewEnumList[TlsPolicy_Kind](s, sz)
}

const schema_c4f4d6e1d8b1a271 = "x\xda\xa4UAh\x1cU\x18\xfe\xbf\xf7fw\x0b6" +
	"\xd9\x1d&!\x8a\x84\xad\xa5\x07[\x9b\xd8\xa4*6Q" +
	"6\x16\x03\xb19t_\xa8\"\xc1\x83\xe3\xe6%;\xcd" +
	"f\xb3\x99\x99h\xb6Z\xd2b\x02\x89\xa4\xa2 h\xb1" +
	"\x94\xa6P\xb1\xea\xa5\x9e4XD\x8dE\xea\xb1(\x1e" +
	"\x9aCT*z,\x1e\x14IG\xde\xcc\xce\xecv\xb2" +
	"\x07\xc1\xdb\xcc\xdb\x7f\xff\xef\xfb\xbf\xef\xff\xde\x1c\xa8\xb0" +
	"\x01\xad\xa7\xe5\xe1\x041\xf1D\"\xe9\xf5\xdf?\xf7\xbb" +
	"\xf6\xc5\xc6\x12\xe9\xf72\xaf\xf4\xd7\x07\xa7?\xbeu\xe1" +
	"\x1f\"\x18'\xd9\x1f\xc62K\x11\x19\x8b\xec(ak" +
	"\xfej\xff\xf7K\x9f\xbd\xa1\xb7\xc2\x9b\xb9x\xe5\xa7\xcd" +
	"\x1f\xff\\\xa7\x04\xd4\xef\xab\xec#\xe3\xb2_y\x89\xe5" +
	"\x08\xde\x87\x8b\x07o\x0f\xff2p\x96D+\xb6\x15\xff" +
	"\xc0\xae\x1b\x9b~\xf1\x06{\x85\xe0=v\xe2\xdd\xbf\xfb" +
	"\xd7^]\xa5\xbb\x1b\xfb\x15O\xf2O\x8dA\xae\x9e\x9e" +
	"\xe2\xaav\xf7\xca\xa1\xa7\xd7\xab\xbb.\xc5\x1a\x0f\"\xc5" +
	"\x01c\x95\xaf\x19\x97y\x07\x91q\x85\xffF\xf0\x06\xdb" +
	"7o\xfe\xfa\xe6\xb9o\xa9\x09\xe5E\xed\xa2qFS" +
	"O\xcb\x9a\xa2\xbc\xeb\xc6\xfa@b\xff\xfb\xd7\x9a\xb1\xf8" +
	"\\[3\xbe\xf2k\xafj\x8a\xc5\xad\xf3\xe7\xce\xdf\xf3" +
	"\xfa\xc2w\xa4w\xb0:%\x82\xd1\x95\xf8\xd98\x94P" +
	"\x85\x8f&\x8e\x12\xbc\x0b\x9f\xbcs\xe3\xf6\xf3\xbd7\xe3" +
	"tY\x8a\x13\x19\xcf$\xae\x1b\xcf\xfa\xd5\"\xa1\xe8>" +
	"\xf0\xcd\x97\xa3\x0f];\xb5\xd1\x8c\xc2\xde\xe4\x9a\xd1\x93" +
	"TO]IE!\xf2)\xa6p0Q\xf2k\xe3\xed" +
	"d\x07\xd1\xc1\xb3\xc9,\xa8\xcb\xb3\xca\x13\xb6t\x9cn" +
	"V0+\xe5J\xdf\xb1\x92\x93\x9f.Y\x85jwz" +
	"\xd8*\x8f\xe5\x01\xb1\x13\x8cH\xef<A\x04\xe8\xf7\x1d" +
	"'\x02\xd3\xdb{\x89<\xb7\xe4\xe4M\xc7q)W\xb4" +
	"\xa7g'\x8a\xea\xe0\x98\xb4\xa7,J\x97MWf\x8b" +
	"\xae[q\"\x00\x04\x00C2m\x8eI[5\xd6\xb8" +
	"F\xa4\x81Ho\xe9%\x12;8\xc4\x1e\x86\xac\xe5\xca" +
	")\x07\xad\x84<\x072\xf5\xd1\x09\xea0N\xf8\xb0Y" +
	"\x98\x94\xe5\xb1\x119N\xa4\x9a\xee\x88\x9a\xee=B$" +
	"\x1e\xe4\x10\x8f0\x00mPg=\xfb\x88\xc4~\x0e\xf1" +
	"8\x83W\x9cv\xdc\xb29%\x89\x08;\x89a'!" +
	"]\x99\xb6]\xa4\x88!\xd5\x00\x85P\x9b\xac3:]" +
	"\x961\x18\xd5r\x0f\x878\xc0\xa0\x878]#u\x9c" +
	"\xb4\xc2\x08\x01|\xd1\x94\xc0\x84*2\x8d\x99Bf;" +
	"b\xde\xcc\xb9E\xf5w\xa1\xa1q\xb7\xb0\xcfwGd" +
	"\"\x16\xa6b\xf1\x02\x87(2\xb4\xc0\xf3\x02\x1aR\xe9" +
	"\xfa\"\x87(1\xb4\xb0;^\x9bo\xa5\xd5G$\xc6" +
	"8D\x85\xa1\x85oym\xe0D\xfa\x94\xaa-r\x08" +
	"\x97!=i\x95\xc7\x90\xae#\x12\x90&d\xe5\x9cY" +
	"p\xc3Qr\x15[\x8e[s\xe1k\xd6\x96\x132z" +
	"\x8bO\"fS\xd2\xae\xfe\x7f\xd7\xc3-rsn\xe5" +
	"\xbfzq\xbc\xe6\xc5P\xdc\x0b\xb5\xa0\xca\x0cJ\x17," +
	"\xd9\x00\x1ee\xb3\xf9\xca\xe5\xcd\xc0\x94\xee\xe1\xd4\xdd\x11" +
	"\xe9\xf5#\xd2\xde\xe7GDM\x17\x08V\x13*\x10(" +
	"\xdel\xa8\xc6\xa1P\x0d\xf6\xb7\xc1\xd2\xc3uK;\xe1" +
	"y\xb5q\xe4\x91\xba{\x9d\xec\x8e:f1\xfb:\xf9" +
	"\x96:V\xae\xce(\xafK\x1cb\x8ea\xfe\xa5 +" +
	"\xd1\xfc\x95\xda *\x00\x99\xc6\xdbJ\xedbvfV" +
	"\xdajG\xa3\xab28\xcf\x15\xa5\x0a02\xe1\xa5\xdf" +
	"|u\x87e\xae\xfa\x9cY\x9a\x8d;\xb4\xbb\x99C\xbd" +
	"\xf5\xa4\xa6&e5Z\xa9\x97U\x83m+\x15\xbf\xaa" +
	"\xc8OG\xfd[\x15\xa6\xa3-B=\xa9P\xe78\xc4" +
	"B\x03\xeai\xa5\xefk\x1cb\x89Ag,\x90qQ" +
	"\xe9u\x8aC\xac0\x80\x07\x1a.\xab\xadZ\xe0\x10o" +
	"1\xe8\x1ao\x83F\xa4\x9f\x19%\x12+\x1c\xe2=\x86" +
	"\x94S\xb6B\x96\xf3\x05i\xbby9\x15\xa5dRV" +
	"\x1b^\xc3dEl\x83dy5kF\x88\xcbqd" +
	"\xea_\xc9@\xdc\x7f\x03\x00\x00\xff\xffj\xfd\xfeM"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c4f4d6e1d8b1a271,
		Nodes: []uint64{
			0x88ddbc04e9781b3b,
			0x8ab888cb3bbd007f,
			0x9940e34bf23385a8,
			0xa17bba3bf9977a36,
			0xa52079c444398c22,
			0xc59c8ee4dce11545,
			0xc69b2c0540c4d320,
			0xc884830b9e9c9ee6,
			0xdc3258f2d394aca0,
			0xdd80c62b5abfc321,
			0xfba0e6ab81a6f86c,
		},
		Compressed: true,
	})
}
