// Code generated by capnpc-go. DO NOT EDIT.

package schema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type TlsZone capnp.Struct

// TlsZone_TypeID is the unique identifier for the type TlsZone.
const TlsZone_TypeID = 0xa17bba3bf9977a36

func NewTlsZone(s *capnp.Segment) (TlsZone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TlsZone(st), err
}

func NewRootTlsZone(s *capnp.Segment) (TlsZone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TlsZone(st), err
}

func ReadRootTlsZone(msg *capnp.Message) (TlsZone, error) {
	root, err := msg.Root()
	return TlsZone(root.Struct()), err
}

func (s TlsZone) String() string {
	str, _ := text.Marshal(0xa17bba3bf9977a36, capnp.Struct(s))
	return str
}

func (s TlsZone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TlsZone) DecodeFromPtr(p capnp.Ptr) TlsZone {
	return TlsZone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TlsZone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TlsZone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TlsZone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TlsZone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TlsZone) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TlsZone) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TlsZone) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TlsZone) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TlsZone) TlsPolicy() (TlsPolicy, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TlsPolicy(p.Struct()), err
}

func (s TlsZone) HasTlsPolicy() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TlsZone) SetTlsPolicy(v TlsPolicy) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewTlsPolicy sets the tlsPolicy field to a newly
// allocated TlsPolicy struct, preferring placement in s's segment.
func (s TlsZone) NewTlsPolicy() (TlsPolicy, error) {
	ss, err := NewTlsPolicy(capnp.Struct(s).Segment())
	if err != nil {
		return TlsPolicy{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// TlsZone_List is a list of TlsZone.
type TlsZone_List = capnp.StructList[TlsZone]

// NewTlsZone creates a new list of TlsZone.
func NewTlsZone_List(s *capnp.Segment, sz int32) (TlsZone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[TlsZone](l), err
}

// TlsZone_Future is a wrapper for a TlsZone promised by a client call.
type TlsZone_Future struct{ *capnp.Future }

func (f TlsZone_Future) Struct() (TlsZone, error) {
	p, err := f.Future.Ptr()
	return TlsZone(p.Struct()), err
}
func (p TlsZone_Future) TlsPolicy() TlsPolicy_Future {
	return TlsPolicy_Future{Future: p.Future.Field(1, nil)}
}

type HttpZone capnp.Struct

// HttpZone_TypeID is the unique identifier for the type HttpZone.
const HttpZone_TypeID = 0xc69b2c0540c4d320

func NewHttpZone(s *capnp.Segment) (HttpZone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HttpZone(st), err
}

func NewRootHttpZone(s *capnp.Segment) (HttpZone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HttpZone(st), err
}

func ReadRootHttpZone(msg *capnp.Message) (HttpZone, error) {
	root, err := msg.Root()
	return HttpZone(root.Struct()), err
}

func (s HttpZone) String() string {
	str, _ := text.Marshal(0xc69b2c0540c4d320, capnp.Struct(s))
	return str
}

func (s HttpZone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HttpZone) DecodeFromPtr(p capnp.Ptr) HttpZone {
	return HttpZone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HttpZone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HttpZone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HttpZone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HttpZone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HttpZone) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HttpZone) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HttpZone) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HttpZone) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HttpZone) HttpPolicies() (HttpPolicy_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return HttpPolicy_List(p.List()), err
}

func (s HttpZone) HasHttpPolicies() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpZone) SetHttpPolicies(v HttpPolicy_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewHttpPolicies sets the httpPolicies field to a newly
// allocated HttpPolicy_List, preferring placement in s's segment.
func (s HttpZone) NewHttpPolicies(n int32) (HttpPolicy_List, error) {
	l, err := NewHttpPolicy_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return HttpPolicy_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// HttpZone_List is a list of HttpZone.
type HttpZone_List = capnp.StructList[HttpZone]

// NewHttpZone creates a new list of HttpZone.
func NewHttpZone_List(s *capnp.Segment, sz int32) (HttpZone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[HttpZone](l), err
}

// HttpZone_Future is a wrapper for a HttpZone promised by a client call.
type HttpZone_Future struct{ *capnp.Future }

func (f HttpZone_Future) Struct() (HttpZone, error) {
	p, err := f.Future.Ptr()
	return HttpZone(p.Struct()), err
}

type HttpPolicy capnp.Struct
type HttpPolicy_Which uint16

const (
	HttpPolicy_Which_pathname HttpPolicy_Which = 0
	HttpPolicy_Which_query    HttpPolicy_Which = 1
	HttpPolicy_Which_header   HttpPolicy_Which = 2
)

func (w HttpPolicy_Which) String() string {
	const s = "pathnamequeryheader"
	switch w {
	case HttpPolicy_Which_pathname:
		return s[0:8]
	case HttpPolicy_Which_query:
		return s[8:13]
	case HttpPolicy_Which_header:
		return s[13:19]

	}
	return "HttpPolicy_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// HttpPolicy_TypeID is the unique identifier for the type HttpPolicy.
const HttpPolicy_TypeID = 0xdc3258f2d394aca0

func NewHttpPolicy(s *capnp.Segment) (HttpPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return HttpPolicy(st), err
}

func NewRootHttpPolicy(s *capnp.Segment) (HttpPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return HttpPolicy(st), err
}

func ReadRootHttpPolicy(msg *capnp.Message) (HttpPolicy, error) {
	root, err := msg.Root()
	return HttpPolicy(root.Struct()), err
}

func (s HttpPolicy) String() string {
	str, _ := text.Marshal(0xdc3258f2d394aca0, capnp.Struct(s))
	return str
}

func (s HttpPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HttpPolicy) DecodeFromPtr(p capnp.Ptr) HttpPolicy {
	return HttpPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HttpPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s HttpPolicy) Which() HttpPolicy_Which {
	return HttpPolicy_Which(capnp.Struct(s).Uint16(0))
}
func (s HttpPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HttpPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HttpPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HttpPolicy) Backend() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HttpPolicy) HasBackend() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HttpPolicy) BackendBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HttpPolicy) SetBackend(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HttpPolicy) Pathname() (Pathname, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != pathname")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Pathname(p.Struct()), err
}

func (s HttpPolicy) HasPathname() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetPathname(v Pathname) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPathname sets the pathname field to a newly
// allocated Pathname struct, preferring placement in s's segment.
func (s HttpPolicy) NewPathname() (Pathname, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewPathname(capnp.Struct(s).Segment())
	if err != nil {
		return Pathname{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) Query() (Query, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != query")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Query(p.Struct()), err
}

func (s HttpPolicy) HasQuery() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetQuery(v Query) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewQuery sets the query field to a newly
// allocated Query struct, preferring placement in s's segment.
func (s HttpPolicy) NewQuery() (Query, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewQuery(capnp.Struct(s).Segment())
	if err != nil {
		return Query{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) Header() (Header, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != header")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Header(p.Struct()), err
}

func (s HttpPolicy) HasHeader() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetHeader(v Header) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewHeader sets the header field to a newly
// allocated Header struct, preferring placement in s's segment.
func (s HttpPolicy) NewHeader() (Header, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewHeader(capnp.Struct(s).Segment())
	if err != nil {
		return Header{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) FixContent() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s HttpPolicy) HasFixContent() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s HttpPolicy) FixContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s HttpPolicy) SetFixContent(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s HttpPolicy) AllowRawAccess() bool {
	return capnp.Struct(s).Bit(16)
}

func (s HttpPolicy) SetAllowRawAccess(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

// HttpPolicy_List is a list of HttpPolicy.
type HttpPolicy_List = capnp.StructList[HttpPolicy]

// NewHttpPolicy creates a new list of HttpPolicy.
func NewHttpPolicy_List(s *capnp.Segment, sz int32) (HttpPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[HttpPolicy](l), err
}

// HttpPolicy_Future is a wrapper for a HttpPolicy promised by a client call.
type HttpPolicy_Future struct{ *capnp.Future }

func (f HttpPolicy_Future) Struct() (HttpPolicy, error) {
	p, err := f.Future.Ptr()
	return HttpPolicy(p.Struct()), err
}
func (p HttpPolicy_Future) Pathname() Pathname_Future {
	return Pathname_Future{Future: p.Future.Field(1, nil)}
}
func (p HttpPolicy_Future) Query() Query_Future {
	return Query_Future{Future: p.Future.Field(1, nil)}
}
func (p HttpPolicy_Future) Header() Header_Future {
	return Header_Future{Future: p.Future.Field(1, nil)}
}

type Pathname capnp.Struct
type Pathname_Which uint16

const (
	Pathname_Which_exact  Pathname_Which = 0
	Pathname_Which_prefix Pathname_Which = 1
	Pathname_Which_regex  Pathname_Which = 2
)

func (w Pathname_Which) String() string {
	const s = "exactprefixregex"
	switch w {
	case Pathname_Which_exact:
		return s[0:5]
	case Pathname_Which_prefix:
		return s[5:11]
	case Pathname_Which_regex:
		return s[11:16]

	}
	return "Pathname_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Pathname_TypeID is the unique identifier for the type Pathname.
const Pathname_TypeID = 0xa52079c444398c22

func NewPathname(s *capnp.Segment) (Pathname, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Pathname(st), err
}

func NewRootPathname(s *capnp.Segment) (Pathname, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Pathname(st), err
}

func ReadRootPathname(msg *capnp.Message) (Pathname, error) {
	root, err := msg.Root()
	return Pathname(root.Struct()), err
}

func (s Pathname) String() string {
	str, _ := text.Marshal(0xa52079c444398c22, capnp.Struct(s))
	return str
}

func (s Pathname) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Pathname) DecodeFromPtr(p capnp.Ptr) Pathname {
	return Pathname(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Pathname) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Pathname) Which() Pathname_Which {
	return Pathname_Which(capnp.Struct(s).Uint16(2))
}
func (s Pathname) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Pathname) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Pathname) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Pathname) Kind() Pathname_Kind {
	return Pathname_Kind(capnp.Struct(s).Uint16(0))
}

func (s Pathname) SetKind(v Pathname_Kind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Pathname) Exact() (string, error) {
	if capnp.Struct(s).Uint16(2) != 0 {
		panic("Which() != exact")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasExact() bool {
	if capnp.Struct(s).Uint16(2) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) ExactBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetExact(v string) error {
	capnp.Struct(s).SetUint16(2, 0)
	return capnp.Struct(s).SetText(0, v)
}

func (s Pathname) Prefix() (string, error) {
	if capnp.Struct(s).Uint16(2) != 1 {
		panic("Which() != prefix")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasPrefix() bool {
	if capnp.Struct(s).Uint16(2) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) PrefixBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetPrefix(v string) error {
	capnp.Struct(s).SetUint16(2, 1)
	return capnp.Struct(s).SetText(0, v)
}

func (s Pathname) Regex() (string, error) {
	if capnp.Struct(s).Uint16(2) != 2 {
		panic("Which() != regex")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasRegex() bool {
	if capnp.Struct(s).Uint16(2) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) RegexBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetRegex(v string) error {
	capnp.Struct(s).SetUint16(2, 2)
	return capnp.Struct(s).SetText(0, v)
}

// Pathname_List is a list of Pathname.
type Pathname_List = capnp.StructList[Pathname]

// NewPathname creates a new list of Pathname.
func NewPathname_List(s *capnp.Segment, sz int32) (Pathname_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Pathname](l), err
}

// Pathname_Future is a wrapper for a Pathname promised by a client call.
type Pathname_Future struct{ *capnp.Future }

func (f Pathname_Future) Struct() (Pathname, error) {
	p, err := f.Future.Ptr()
	return Pathname(p.Struct()), err
}

type Pathname_Kind uint16

// Pathname_Kind_TypeID is the unique identifier for the type Pathname_Kind.
const Pathname_Kind_TypeID = 0xc884830b9e9c9ee6

// Values of Pathname_Kind.
const (
	Pathname_Kind_exact  Pathname_Kind = 0
	Pathname_Kind_prefix Pathname_Kind = 1
	Pathname_Kind_regex  Pathname_Kind = 2
)

// String returns the enum's constant name.
func (c Pathname_Kind) String() string {
	switch c {
	case Pathname_Kind_exact:
		return "exact"
	case Pathname_Kind_prefix:
		return "prefix"
	case Pathname_Kind_regex:
		return "regex"

	default:
		return ""
	}
}

// Pathname_KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Pathname_KindFromString(c string) Pathname_Kind {
	switch c {
	case "exact":
		return Pathname_Kind_exact
	case "prefix":
		return Pathname_Kind_prefix
	case "regex":
		return Pathname_Kind_regex

	default:
		return 0
	}
}

type Pathname_Kind_List = capnp.EnumList[Pathname_Kind]

func NewPathname_Kind_List(s *capnp.Segment, sz int32) (Pathname_Kind_List, error) {
	return capnp.NewEnumList[Pathname_Kind](s, sz)
}

type Query capnp.Struct

// Query_TypeID is the unique identifier for the type Query.
const Query_TypeID = 0xc59c8ee4dce11545

func NewQuery(s *capnp.Segment) (Query, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Query(st), err
}

func NewRootQuery(s *capnp.Segment) (Query, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Query(st), err
}

func ReadRootQuery(msg *capnp.Message) (Query, error) {
	root, err := msg.Root()
	return Query(root.Struct()), err
}

func (s Query) String() string {
	str, _ := text.Marshal(0xc59c8ee4dce11545, capnp.Struct(s))
	return str
}

func (s Query) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Query) DecodeFromPtr(p capnp.Ptr) Query {
	return Query(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Query) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Query) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Query) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Query) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Query) Items() (KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValue_List(p.List()), err
}

func (s Query) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Query) SetItems(v KeyValue_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated KeyValue_List, preferring placement in s's segment.
func (s Query) NewItems(n int32) (KeyValue_List, error) {
	l, err := NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Query_List is a list of Query.
type Query_List = capnp.StructList[Query]

// NewQuery creates a new list of Query.
func NewQuery_List(s *capnp.Segment, sz int32) (Query_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Query](l), err
}

// Query_Future is a wrapper for a Query promised by a client call.
type Query_Future struct{ *capnp.Future }

func (f Query_Future) Struct() (Query, error) {
	p, err := f.Future.Ptr()
	return Query(p.Struct()), err
}

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0x8ab888cb3bbd007f

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0x8ab888cb3bbd007f, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Items() (KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValue_List(p.List()), err
}

func (s Header) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) SetItems(v KeyValue_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated KeyValue_List, preferring placement in s's segment.
func (s Header) NewItems(n int32) (KeyValue_List, error) {
	l, err := NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type KeyValue capnp.Struct

// KeyValue_TypeID is the unique identifier for the type KeyValue.
const KeyValue_TypeID = 0xdd80c62b5abfc321

func NewKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func NewRootKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func ReadRootKeyValue(msg *capnp.Message) (KeyValue, error) {
	root, err := msg.Root()
	return KeyValue(root.Struct()), err
}

func (s KeyValue) String() string {
	str, _ := text.Marshal(0xdd80c62b5abfc321, capnp.Struct(s))
	return str
}

func (s KeyValue) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (KeyValue) DecodeFromPtr(p capnp.Ptr) KeyValue {
	return KeyValue(capnp.Struct{}.DecodeFromPtr(p))
}

func (s KeyValue) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s KeyValue) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s KeyValue) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s KeyValue) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s KeyValue) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s KeyValue) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s KeyValue) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s KeyValue) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s KeyValue) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s KeyValue) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s KeyValue) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s KeyValue) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// KeyValue_List is a list of KeyValue.
type KeyValue_List = capnp.StructList[KeyValue]

// NewKeyValue creates a new list of KeyValue.
func NewKeyValue_List(s *capnp.Segment, sz int32) (KeyValue_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[KeyValue](l), err
}

// KeyValue_Future is a wrapper for a KeyValue promised by a client call.
type KeyValue_Future struct{ *capnp.Future }

func (f KeyValue_Future) Struct() (KeyValue, error) {
	p, err := f.Future.Ptr()
	return KeyValue(p.Struct()), err
}

type BackendRef capnp.Struct

// BackendRef_TypeID is the unique identifier for the type BackendRef.
const BackendRef_TypeID = 0x9940e34bf23385a8

func NewBackendRef(s *capnp.Segment) (BackendRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return BackendRef(st), err
}

func NewRootBackendRef(s *capnp.Segment) (BackendRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return BackendRef(st), err
}

func ReadRootBackendRef(msg *capnp.Message) (BackendRef, error) {
	root, err := msg.Root()
	return BackendRef(root.Struct()), err
}

func (s BackendRef) String() string {
	str, _ := text.Marshal(0x9940e34bf23385a8, capnp.Struct(s))
	return str
}

func (s BackendRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BackendRef) DecodeFromPtr(p capnp.Ptr) BackendRef {
	return BackendRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BackendRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BackendRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BackendRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BackendRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BackendRef) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BackendRef) HasHostname() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BackendRef) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BackendRef) SetHostname(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BackendRef) Port() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s BackendRef) SetPort(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

// BackendRef_List is a list of BackendRef.
type BackendRef_List = capnp.StructList[BackendRef]

// NewBackendRef creates a new list of BackendRef.
func NewBackendRef_List(s *capnp.Segment, sz int32) (BackendRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[BackendRef](l), err
}

// BackendRef_Future is a wrapper for a BackendRef promised by a client call.
type BackendRef_Future struct{ *capnp.Future }

func (f BackendRef_Future) Struct() (BackendRef, error) {
	p, err := f.Future.Ptr()
	return BackendRef(p.Struct()), err
}

type TlsPolicy capnp.Struct

// TlsPolicy_TypeID is the unique identifier for the type TlsPolicy.
const TlsPolicy_TypeID = 0xfba0e6ab81a6f86c

func NewTlsPolicy(s *capnp.Segment) (TlsPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return TlsPolicy(st), err
}

func NewRootTlsPolicy(s *capnp.Segment) (TlsPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return TlsPolicy(st), err
}

func ReadRootTlsPolicy(msg *capnp.Message) (TlsPolicy, error) {
	root, err := msg.Root()
	return TlsPolicy(root.Struct()), err
}

func (s TlsPolicy) String() string {
	str, _ := text.Marshal(0xfba0e6ab81a6f86c, capnp.Struct(s))
	return str
}

func (s TlsPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TlsPolicy) DecodeFromPtr(p capnp.Ptr) TlsPolicy {
	return TlsPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TlsPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TlsPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TlsPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TlsPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TlsPolicy) Sni() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TlsPolicy) HasSni() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TlsPolicy) SniBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetSni(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TlsPolicy) CertPem() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TlsPolicy) HasCertPem() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TlsPolicy) CertPemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetCertPem(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TlsPolicy) KeyPem() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TlsPolicy) HasKeyPem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TlsPolicy) KeyPemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetKeyPem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TlsPolicy) Kind() TlsPolicy_Kind {
	return TlsPolicy_Kind(capnp.Struct(s).Uint16(0))
}

func (s TlsPolicy) SetKind(v TlsPolicy_Kind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s TlsPolicy) BackendRef() (BackendRef, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return BackendRef(p.Struct()), err
}

func (s TlsPolicy) HasBackendRef() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TlsPolicy) SetBackendRef(v BackendRef) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewBackendRef sets the backendRef field to a newly
// allocated BackendRef struct, preferring placement in s's segment.
func (s TlsPolicy) NewBackendRef() (BackendRef, error) {
	ss, err := NewBackendRef(capnp.Struct(s).Segment())
	if err != nil {
		return BackendRef{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// TlsPolicy_List is a list of TlsPolicy.
type TlsPolicy_List = capnp.StructList[TlsPolicy]

// NewTlsPolicy creates a new list of TlsPolicy.
func NewTlsPolicy_List(s *capnp.Segment, sz int32) (TlsPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[TlsPolicy](l), err
}

// TlsPolicy_Future is a wrapper for a TlsPolicy promised by a client call.
type TlsPolicy_Future struct{ *capnp.Future }

func (f TlsPolicy_Future) Struct() (TlsPolicy, error) {
	p, err := f.Future.Ptr()
	return TlsPolicy(p.Struct()), err
}
func (p TlsPolicy_Future) BackendRef() BackendRef_Future {
	return BackendRef_Future{Future: p.Future.Field(3, nil)}
}

type TlsPolicy_Kind uint16

// TlsPolicy_Kind_TypeID is the unique identifier for the type TlsPolicy_Kind.
const TlsPolicy_Kind_TypeID = 0x88ddbc04e9781b3b

// Values of TlsPolicy_Kind.
const (
	TlsPolicy_Kind_tlsPassthrough TlsPolicy_Kind = 0
	TlsPolicy_Kind_tlsTerminate   TlsPolicy_Kind = 1
	TlsPolicy_Kind_https          TlsPolicy_Kind = 2
)

// String returns the enum's constant name.
func (c TlsPolicy_Kind) String() string {
	switch c {
	case TlsPolicy_Kind_tlsPassthrough:
		return "tlsPassthrough"
	case TlsPolicy_Kind_tlsTerminate:
		return "tlsTerminate"
	case TlsPolicy_Kind_https:
		return "https"

	default:
		return ""
	}
}

// TlsPolicy_KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TlsPolicy_KindFromString(c string) TlsPolicy_Kind {
	switch c {
	case "tlsPassthrough":
		return TlsPolicy_Kind_tlsPassthrough
	case "tlsTerminate":
		return TlsPolicy_Kind_tlsTerminate
	case "https":
		return TlsPolicy_Kind_https

	default:
		return 0
	}
}

type TlsPolicy_Kind_List = capnp.EnumList[TlsPolicy_Kind]

func NewTlsPolicy_Kind_List(s *capnp.Segment, sz int32) (TlsPolicy_Kind_List, error) {
	return capnp.NewEnumList[TlsPolicy_Kind](s, sz)
}

const schema_c4f4d6e1d8b1a271 = "x\xda\xa4Vo\x88T\xd5\x1b~\x9fs\xee\xec\x15~" +
	"\xeeo\xe6rG\xec\x0f\xc3\x98H\x7f\xcc\xbf3\x11\xb5" +
	"\x06c[\x82\xb4\x1f\x9c\xb3H\xc5R\xd0u\xe6\xacs" +
	"\xdd\x99;\xe3\xdc\xbb\xb9c\xc9*\xed\xc2\x16k$\x18" +
	"%m\xb2\x85\x86\xd2\x06\x05\x09\x1aIA\x9b\x04\xd1'" +
	")\xfa\xa0\x1f\xa44\xfc\xa8\xb4\x90\xc4z\xe3\xdc\x99\xb9" +
	"3N+\xbb\xd0\xc7sx9\xcf\xf3\xbe\xcf\xf3\xbc\xf7" +
	"n:\xc1\xb6j\x9b\xbb7F\x88\x89\xa7\"]\xfe\x96" +
	"\xfbG\xaek__\x9e \xe3!\xe6\x17\xff\xfa\xe4\xd0" +
	"\xa7\xd7\xa6\xff&B\xfa\x00\xdb\x05\xf3\x08\xd3\x89\xcc\xc3" +
	"l\x07a~\xf4\xfc\x96\x1f'\xce\xbee$\xe0\xef\xfd" +
	"\xf8\x8b_\xaf\xfc\xf2\xe7,E\xa0\x13\xa5O\xb3\xd50" +
	"\xcf\x05\xa5gX\x86\xe0\x9f\x1aO\xdf\xec\xfbm\xeb1" +
	"\x12\x09\xfc\xab\xfa*\xeb\x859\x17T\xdf`\xfb\x08\xfe" +
	"\xe3\xfb\xdf\xbb\xb5\xe5\xab\xd7>\xa2;\x9fV\x15i\xc1" +
	"\xd7\xc2\xb4\xb8*~\x99\xab\xe2\xd5\x93O>;[[" +
	"u\xb2\xe3\xe9m\xd09\x90>\xcfS0\x7f\xe2+\x89" +
	"\xcc\x9f\xf9\x1f\x04\x7f\xdb\x8a+\x97~\x7f{\xea{Z" +
	"\x88\xb6v\x1f\xccsZ@[S\xb4W]\x9c\xdd\x1a" +
	"Y\xf7\xc1\x85\x85\x88\\\xd5R0\xe7\x82\xe2\x1b\x9a\"" +
	"r\xed\xf8\xd4\xf1\xff\xbd1\xf6\x03\x19\x0f\xb2\x16+B" +
	"\xda\x8a\x0c\xc0\x1c\x8e\xa8\xca\xbd\x91\x1d\x04\x7fz\xe6\xe8" +
	"\xc5\x9b/\xa6.uR\xe6:'J\x8fGza\xbe" +
	"\xab\xca\xd3G\"/\x80\xe0?\xf0\xdd7\x03\x8f^8" +
	"xy!\x1a\xd7\xbbR0ou\xa9\xc7\xe7\xba\x14\x8d" +
	"P\xb2\x8eQk\xc1\xf4\xf4\x1e\x98\x96\xbe\x92(m\xeb" +
	"I\xd0z\xdfvvW\xa5\xebn\xd4\xdc\\A\x96\xac" +
	"\x8d\x8d\xf3\x86\x9cUq*=;\x8bn\xb6\\\xb4s" +
	"\xb5\x0d}\xba\xed\xe4\xb3\x80X\x0eFd$\xf6\x13\x01" +
	"\xc6\xbd{\x88\xc0\x8c\x15)\"\xdf+\xbaY\xcbu=" +
	"\xca\x14\xaa\xe5\xe1\xdd\x05u\xb1SVK6E\x1d\xcb" +
	"\x93\xc9\x82\xe7U\xdc\x10\x8f/\x88\xb7]Zz^V" +
	"\x15\x8e\xc65\"\x0dDFw\x8aH,\xe3\x10k\x18" +
	"\x92\xb6'K.\xfeO\xc8r \xd6\x1a\x0dA]." +
	"\xd2N\xaf\x95\x1b\x92N\xbe_\x0e\x92\x82X\x16B<" +
	"\xf2\x1c\x91x\x98C<\xc6\x00\xc4\xa1\xee6\xaf%\x12" +
	"\xeb8\xc4\x13\x0c~\xa1\xecz\x8eU\x92D\x84\xe5\xc4" +
	"\xb0\x9c\x10\xad\x94\xab\x1etb\xd0\xdb\x80\xf9\xdd\xe6\x18" +
	"\x1d(;\xb2\x03U!\xac\xe1\x10\x9b\x18\x8c&\xec\xfa" +
	"\xfe\x16lTA6\xf1\x82\x01+1\x085\xc4\xda\xa3" +
	"\x89\xd8\xa2\x04\xb2\x96\x97,\xa8\xd7\x84\x86v\xabbm" +
	"\xb4\xcfv\xf2\"\x16\x92\xb2\x14\xa9\x978D\x81\xa1\x1b" +
	"\xbe_g%\x95\x06\xafp\x88\"C7\xbb\xed\xc7\x03" +
	"\x17\xd8=D\"\xcf!*\x0c\xdd|\xde\x8f\x83\x13\x19" +
	"%U[\xe0\x10\x1eCt\xc8v\xf2\x88\xb6\x10\x09\x88" +
	"\x12\x92r\xc4\xcay\xcd\xce2\x95\xaa\x1c\xb4G\x9a\xc7" +
	"dU\xee\x96\xe1i\x91\xc6\xc4\xb0\xe4\xd5\xda\x7f7\xcc" +
	"]\xfc\xe8y\xc9\xcaR\x85\xdb\xd3\x10n{\xa7p\xca" +
	"\xf9J9\x8a\xe6l\xd9\xc6%\xdc\x03K2o\xd6\xf2" +
	"\x02\x057\xf4\xd9\xfc\x8e(\xa6\x82(\xae\xe8\x09\xa2\xa8" +
	"z\xafO\xb71\xd5\xfa4\x17y{{\x83a\xae\x16" +
	"\x04\xe3\x9e\xb0\xd3c\xbdD\xe2(\x87\x98fH\xc0\xf7" +
	"\x1b\xbd~\xa8\xf22\xc5!N1$\xd8mu\xad\xa8" +
	"\x9cT\x83\x9f\xe6\x103\x0c\x09>\xaf\xae\x95!N+" +
	"\x9b\x9c\xe0\x10\x9f3\x18\x1a\x8bC#2>\x1b \x12" +
	"3\x1c\xe2,\x83\x11\x89\xc5\x11!2\xce\xec'\x12_" +
	"r\x88o\x19Fw\xd5\xd3\x1a\x8e\xb1\xd2\x18\x80\xca`" +
	"\xac}\xc3*\xff'\xf7\x0e\xcb\xaa\xcaE\xb8\xe0\xeb\xf7" +
	"\x99\x82\xb4\xf2\xb2\x8aX\xf3s\xd5\x88\xcb\xa0=\xf2L" +
	"\xd9\xf1$q'\xf4\xa1o\x15\x8b\xe5}\xfd\xd6>\xca" +
	"<\x9d\xcbI\xd7\x05\x88\x01\x8b\xba\xa4O\xd6\x92\xcf[" +
	"\xc5\xe1N\x97\xac^\xc8%\xa9\xd6\xa6\xd1\x87d-4" +
	"\xfd\xab\xea\x81%\x9a~g\xd1\xcd\xd4\xe5\x0a\xe2\xdc\xfa" +
	"d7\xe3\x1c\x0fI\x1cP$F8\xc4X\x1b\x89C" +
	"J\xd5\xd79\xc4\x04\x83\xc1X]\xbcq\xa5\xd2A\x0e" +
	"1\xc9\x00^W\xeeMe\xf41\x0e\xf1\x8eR\x8e\xd7" +
	"\x95;\xac\x94\x9b\xe4\x10\xef3\xe8\xaec7I\x8f\xe6" +
	"d\xd5\xcb\xcaR\x18\xeb!Yk;6WA\xc8\xb6" +
	"\xbe\x0a\xfc\x86\xcc\xfd\xc4\xe5 b\xad_\x85\xbaP\xff" +
	"\x04\x00\x00\xff\xff8\xc9T\xe2"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c4f4d6e1d8b1a271,
		Nodes: []uint64{
			0x88ddbc04e9781b3b,
			0x8ab888cb3bbd007f,
			0x9940e34bf23385a8,
			0xa17bba3bf9977a36,
			0xa52079c444398c22,
			0xc59c8ee4dce11545,
			0xc69b2c0540c4d320,
			0xc884830b9e9c9ee6,
			0xdc3258f2d394aca0,
			0xdd80c62b5abfc321,
			0xfba0e6ab81a6f86c,
		},
		Compressed: true,
	})
}
