// Code generated by capnpc-go. DO NOT EDIT.

package schema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type TlsZone capnp.Struct

// TlsZone_TypeID is the unique identifier for the type TlsZone.
const TlsZone_TypeID = 0xa17bba3bf9977a36

func NewTlsZone(s *capnp.Segment) (TlsZone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TlsZone(st), err
}

func NewRootTlsZone(s *capnp.Segment) (TlsZone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return TlsZone(st), err
}

func ReadRootTlsZone(msg *capnp.Message) (TlsZone, error) {
	root, err := msg.Root()
	return TlsZone(root.Struct()), err
}

func (s TlsZone) String() string {
	str, _ := text.Marshal(0xa17bba3bf9977a36, capnp.Struct(s))
	return str
}

func (s TlsZone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TlsZone) DecodeFromPtr(p capnp.Ptr) TlsZone {
	return TlsZone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TlsZone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TlsZone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TlsZone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TlsZone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TlsZone) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TlsZone) HasHostname() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TlsZone) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TlsZone) SetHostname(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TlsZone) TlsPolicy() (TlsPolicy, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TlsPolicy(p.Struct()), err
}

func (s TlsZone) HasTlsPolicy() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TlsZone) SetTlsPolicy(v TlsPolicy) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewTlsPolicy sets the tlsPolicy field to a newly
// allocated TlsPolicy struct, preferring placement in s's segment.
func (s TlsZone) NewTlsPolicy() (TlsPolicy, error) {
	ss, err := NewTlsPolicy(capnp.Struct(s).Segment())
	if err != nil {
		return TlsPolicy{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// TlsZone_List is a list of TlsZone.
type TlsZone_List = capnp.StructList[TlsZone]

// NewTlsZone creates a new list of TlsZone.
func NewTlsZone_List(s *capnp.Segment, sz int32) (TlsZone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[TlsZone](l), err
}

// TlsZone_Future is a wrapper for a TlsZone promised by a client call.
type TlsZone_Future struct{ *capnp.Future }

func (f TlsZone_Future) Struct() (TlsZone, error) {
	p, err := f.Future.Ptr()
	return TlsZone(p.Struct()), err
}
func (p TlsZone_Future) TlsPolicy() TlsPolicy_Future {
	return TlsPolicy_Future{Future: p.Future.Field(1, nil)}
}

type HttpZone capnp.Struct

// HttpZone_TypeID is the unique identifier for the type HttpZone.
const HttpZone_TypeID = 0xc69b2c0540c4d320

func NewHttpZone(s *capnp.Segment) (HttpZone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HttpZone(st), err
}

func NewRootHttpZone(s *capnp.Segment) (HttpZone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HttpZone(st), err
}

func ReadRootHttpZone(msg *capnp.Message) (HttpZone, error) {
	root, err := msg.Root()
	return HttpZone(root.Struct()), err
}

func (s HttpZone) String() string {
	str, _ := text.Marshal(0xc69b2c0540c4d320, capnp.Struct(s))
	return str
}

func (s HttpZone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HttpZone) DecodeFromPtr(p capnp.Ptr) HttpZone {
	return HttpZone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HttpZone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HttpZone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HttpZone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HttpZone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HttpZone) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HttpZone) HasHostname() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HttpZone) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HttpZone) SetHostname(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HttpZone) HttpPolicies() (HttpPolicy_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return HttpPolicy_List(p.List()), err
}

func (s HttpZone) HasHttpPolicies() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpZone) SetHttpPolicies(v HttpPolicy_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewHttpPolicies sets the httpPolicies field to a newly
// allocated HttpPolicy_List, preferring placement in s's segment.
func (s HttpZone) NewHttpPolicies(n int32) (HttpPolicy_List, error) {
	l, err := NewHttpPolicy_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return HttpPolicy_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// HttpZone_List is a list of HttpZone.
type HttpZone_List = capnp.StructList[HttpZone]

// NewHttpZone creates a new list of HttpZone.
func NewHttpZone_List(s *capnp.Segment, sz int32) (HttpZone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[HttpZone](l), err
}

// HttpZone_Future is a wrapper for a HttpZone promised by a client call.
type HttpZone_Future struct{ *capnp.Future }

func (f HttpZone_Future) Struct() (HttpZone, error) {
	p, err := f.Future.Ptr()
	return HttpZone(p.Struct()), err
}

type HttpPolicy capnp.Struct
type HttpPolicy_Which uint16

const (
	HttpPolicy_Which_pathname HttpPolicy_Which = 0
	HttpPolicy_Which_query    HttpPolicy_Which = 1
	HttpPolicy_Which_header   HttpPolicy_Which = 2
)

func (w HttpPolicy_Which) String() string {
	const s = "pathnamequeryheader"
	switch w {
	case HttpPolicy_Which_pathname:
		return s[0:8]
	case HttpPolicy_Which_query:
		return s[8:13]
	case HttpPolicy_Which_header:
		return s[13:19]

	}
	return "HttpPolicy_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// HttpPolicy_TypeID is the unique identifier for the type HttpPolicy.
const HttpPolicy_TypeID = 0xdc3258f2d394aca0

func NewHttpPolicy(s *capnp.Segment) (HttpPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return HttpPolicy(st), err
}

func NewRootHttpPolicy(s *capnp.Segment) (HttpPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return HttpPolicy(st), err
}

func ReadRootHttpPolicy(msg *capnp.Message) (HttpPolicy, error) {
	root, err := msg.Root()
	return HttpPolicy(root.Struct()), err
}

func (s HttpPolicy) String() string {
	str, _ := text.Marshal(0xdc3258f2d394aca0, capnp.Struct(s))
	return str
}

func (s HttpPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HttpPolicy) DecodeFromPtr(p capnp.Ptr) HttpPolicy {
	return HttpPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HttpPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s HttpPolicy) Which() HttpPolicy_Which {
	return HttpPolicy_Which(capnp.Struct(s).Uint16(0))
}
func (s HttpPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HttpPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HttpPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HttpPolicy) Backend() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HttpPolicy) HasBackend() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HttpPolicy) BackendBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HttpPolicy) SetBackend(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HttpPolicy) Pathname() (Pathname, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != pathname")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Pathname(p.Struct()), err
}

func (s HttpPolicy) HasPathname() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetPathname(v Pathname) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPathname sets the pathname field to a newly
// allocated Pathname struct, preferring placement in s's segment.
func (s HttpPolicy) NewPathname() (Pathname, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewPathname(capnp.Struct(s).Segment())
	if err != nil {
		return Pathname{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) Query() (Query, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != query")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Query(p.Struct()), err
}

func (s HttpPolicy) HasQuery() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetQuery(v Query) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewQuery sets the query field to a newly
// allocated Query struct, preferring placement in s's segment.
func (s HttpPolicy) NewQuery() (Query, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewQuery(capnp.Struct(s).Segment())
	if err != nil {
		return Query{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) Header() (Header, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != header")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return Header(p.Struct()), err
}

func (s HttpPolicy) HasHeader() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s HttpPolicy) SetHeader(v Header) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewHeader sets the header field to a newly
// allocated Header struct, preferring placement in s's segment.
func (s HttpPolicy) NewHeader() (Header, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewHeader(capnp.Struct(s).Segment())
	if err != nil {
		return Header{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HttpPolicy) FixContent() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s HttpPolicy) HasFixContent() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s HttpPolicy) FixContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s HttpPolicy) SetFixContent(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s HttpPolicy) AllowRawAccess() bool {
	return capnp.Struct(s).Bit(16)
}

func (s HttpPolicy) SetAllowRawAccess(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

// HttpPolicy_List is a list of HttpPolicy.
type HttpPolicy_List = capnp.StructList[HttpPolicy]

// NewHttpPolicy creates a new list of HttpPolicy.
func NewHttpPolicy_List(s *capnp.Segment, sz int32) (HttpPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[HttpPolicy](l), err
}

// HttpPolicy_Future is a wrapper for a HttpPolicy promised by a client call.
type HttpPolicy_Future struct{ *capnp.Future }

func (f HttpPolicy_Future) Struct() (HttpPolicy, error) {
	p, err := f.Future.Ptr()
	return HttpPolicy(p.Struct()), err
}
func (p HttpPolicy_Future) Pathname() Pathname_Future {
	return Pathname_Future{Future: p.Future.Field(1, nil)}
}
func (p HttpPolicy_Future) Query() Query_Future {
	return Query_Future{Future: p.Future.Field(1, nil)}
}
func (p HttpPolicy_Future) Header() Header_Future {
	return Header_Future{Future: p.Future.Field(1, nil)}
}

type Pathname capnp.Struct
type Pathname_Which uint16

const (
	Pathname_Which_exact  Pathname_Which = 0
	Pathname_Which_prefix Pathname_Which = 1
	Pathname_Which_regex  Pathname_Which = 2
)

func (w Pathname_Which) String() string {
	const s = "exactprefixregex"
	switch w {
	case Pathname_Which_exact:
		return s[0:5]
	case Pathname_Which_prefix:
		return s[5:11]
	case Pathname_Which_regex:
		return s[11:16]

	}
	return "Pathname_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Pathname_TypeID is the unique identifier for the type Pathname.
const Pathname_TypeID = 0xa52079c444398c22

func NewPathname(s *capnp.Segment) (Pathname, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Pathname(st), err
}

func NewRootPathname(s *capnp.Segment) (Pathname, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Pathname(st), err
}

func ReadRootPathname(msg *capnp.Message) (Pathname, error) {
	root, err := msg.Root()
	return Pathname(root.Struct()), err
}

func (s Pathname) String() string {
	str, _ := text.Marshal(0xa52079c444398c22, capnp.Struct(s))
	return str
}

func (s Pathname) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Pathname) DecodeFromPtr(p capnp.Ptr) Pathname {
	return Pathname(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Pathname) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Pathname) Which() Pathname_Which {
	return Pathname_Which(capnp.Struct(s).Uint16(2))
}
func (s Pathname) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Pathname) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Pathname) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Pathname) Kind() Pathname_Kind {
	return Pathname_Kind(capnp.Struct(s).Uint16(0))
}

func (s Pathname) SetKind(v Pathname_Kind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Pathname) Exact() (string, error) {
	if capnp.Struct(s).Uint16(2) != 0 {
		panic("Which() != exact")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasExact() bool {
	if capnp.Struct(s).Uint16(2) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) ExactBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetExact(v string) error {
	capnp.Struct(s).SetUint16(2, 0)
	return capnp.Struct(s).SetText(0, v)
}

func (s Pathname) Prefix() (string, error) {
	if capnp.Struct(s).Uint16(2) != 1 {
		panic("Which() != prefix")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasPrefix() bool {
	if capnp.Struct(s).Uint16(2) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) PrefixBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetPrefix(v string) error {
	capnp.Struct(s).SetUint16(2, 1)
	return capnp.Struct(s).SetText(0, v)
}

func (s Pathname) Regex() (string, error) {
	if capnp.Struct(s).Uint16(2) != 2 {
		panic("Which() != regex")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Pathname) HasRegex() bool {
	if capnp.Struct(s).Uint16(2) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Pathname) RegexBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Pathname) SetRegex(v string) error {
	capnp.Struct(s).SetUint16(2, 2)
	return capnp.Struct(s).SetText(0, v)
}

// Pathname_List is a list of Pathname.
type Pathname_List = capnp.StructList[Pathname]

// NewPathname creates a new list of Pathname.
func NewPathname_List(s *capnp.Segment, sz int32) (Pathname_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Pathname](l), err
}

// Pathname_Future is a wrapper for a Pathname promised by a client call.
type Pathname_Future struct{ *capnp.Future }

func (f Pathname_Future) Struct() (Pathname, error) {
	p, err := f.Future.Ptr()
	return Pathname(p.Struct()), err
}

type Pathname_Kind uint16

// Pathname_Kind_TypeID is the unique identifier for the type Pathname_Kind.
const Pathname_Kind_TypeID = 0xc884830b9e9c9ee6

// Values of Pathname_Kind.
const (
	Pathname_Kind_exact  Pathname_Kind = 0
	Pathname_Kind_prefix Pathname_Kind = 1
	Pathname_Kind_regex  Pathname_Kind = 2
)

// String returns the enum's constant name.
func (c Pathname_Kind) String() string {
	switch c {
	case Pathname_Kind_exact:
		return "exact"
	case Pathname_Kind_prefix:
		return "prefix"
	case Pathname_Kind_regex:
		return "regex"

	default:
		return ""
	}
}

// Pathname_KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func Pathname_KindFromString(c string) Pathname_Kind {
	switch c {
	case "exact":
		return Pathname_Kind_exact
	case "prefix":
		return Pathname_Kind_prefix
	case "regex":
		return Pathname_Kind_regex

	default:
		return 0
	}
}

type Pathname_Kind_List = capnp.EnumList[Pathname_Kind]

func NewPathname_Kind_List(s *capnp.Segment, sz int32) (Pathname_Kind_List, error) {
	return capnp.NewEnumList[Pathname_Kind](s, sz)
}

type Query capnp.Struct

// Query_TypeID is the unique identifier for the type Query.
const Query_TypeID = 0xc59c8ee4dce11545

func NewQuery(s *capnp.Segment) (Query, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Query(st), err
}

func NewRootQuery(s *capnp.Segment) (Query, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Query(st), err
}

func ReadRootQuery(msg *capnp.Message) (Query, error) {
	root, err := msg.Root()
	return Query(root.Struct()), err
}

func (s Query) String() string {
	str, _ := text.Marshal(0xc59c8ee4dce11545, capnp.Struct(s))
	return str
}

func (s Query) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Query) DecodeFromPtr(p capnp.Ptr) Query {
	return Query(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Query) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Query) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Query) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Query) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Query) Items() (KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValue_List(p.List()), err
}

func (s Query) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Query) SetItems(v KeyValue_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated KeyValue_List, preferring placement in s's segment.
func (s Query) NewItems(n int32) (KeyValue_List, error) {
	l, err := NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Query_List is a list of Query.
type Query_List = capnp.StructList[Query]

// NewQuery creates a new list of Query.
func NewQuery_List(s *capnp.Segment, sz int32) (Query_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Query](l), err
}

// Query_Future is a wrapper for a Query promised by a client call.
type Query_Future struct{ *capnp.Future }

func (f Query_Future) Struct() (Query, error) {
	p, err := f.Future.Ptr()
	return Query(p.Struct()), err
}

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0x8ab888cb3bbd007f

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0x8ab888cb3bbd007f, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Items() (KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return KeyValue_List(p.List()), err
}

func (s Header) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) SetItems(v KeyValue_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated KeyValue_List, preferring placement in s's segment.
func (s Header) NewItems(n int32) (KeyValue_List, error) {
	l, err := NewKeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type KeyValue capnp.Struct

// KeyValue_TypeID is the unique identifier for the type KeyValue.
const KeyValue_TypeID = 0xdd80c62b5abfc321

func NewKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func NewRootKeyValue(s *capnp.Segment) (KeyValue, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return KeyValue(st), err
}

func ReadRootKeyValue(msg *capnp.Message) (KeyValue, error) {
	root, err := msg.Root()
	return KeyValue(root.Struct()), err
}

func (s KeyValue) String() string {
	str, _ := text.Marshal(0xdd80c62b5abfc321, capnp.Struct(s))
	return str
}

func (s KeyValue) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (KeyValue) DecodeFromPtr(p capnp.Ptr) KeyValue {
	return KeyValue(capnp.Struct{}.DecodeFromPtr(p))
}

func (s KeyValue) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s KeyValue) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s KeyValue) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s KeyValue) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s KeyValue) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s KeyValue) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s KeyValue) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s KeyValue) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s KeyValue) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s KeyValue) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s KeyValue) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s KeyValue) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// KeyValue_List is a list of KeyValue.
type KeyValue_List = capnp.StructList[KeyValue]

// NewKeyValue creates a new list of KeyValue.
func NewKeyValue_List(s *capnp.Segment, sz int32) (KeyValue_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[KeyValue](l), err
}

// KeyValue_Future is a wrapper for a KeyValue promised by a client call.
type KeyValue_Future struct{ *capnp.Future }

func (f KeyValue_Future) Struct() (KeyValue, error) {
	p, err := f.Future.Ptr()
	return KeyValue(p.Struct()), err
}

type BackendRef capnp.Struct

// BackendRef_TypeID is the unique identifier for the type BackendRef.
const BackendRef_TypeID = 0x9940e34bf23385a8

func NewBackendRef(s *capnp.Segment) (BackendRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return BackendRef(st), err
}

func NewRootBackendRef(s *capnp.Segment) (BackendRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return BackendRef(st), err
}

func ReadRootBackendRef(msg *capnp.Message) (BackendRef, error) {
	root, err := msg.Root()
	return BackendRef(root.Struct()), err
}

func (s BackendRef) String() string {
	str, _ := text.Marshal(0x9940e34bf23385a8, capnp.Struct(s))
	return str
}

func (s BackendRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BackendRef) DecodeFromPtr(p capnp.Ptr) BackendRef {
	return BackendRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BackendRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BackendRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BackendRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BackendRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BackendRef) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s BackendRef) HasHostname() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BackendRef) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s BackendRef) SetHostname(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s BackendRef) Port() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s BackendRef) SetPort(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

// BackendRef_List is a list of BackendRef.
type BackendRef_List = capnp.StructList[BackendRef]

// NewBackendRef creates a new list of BackendRef.
func NewBackendRef_List(s *capnp.Segment, sz int32) (BackendRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[BackendRef](l), err
}

// BackendRef_Future is a wrapper for a BackendRef promised by a client call.
type BackendRef_Future struct{ *capnp.Future }

func (f BackendRef_Future) Struct() (BackendRef, error) {
	p, err := f.Future.Ptr()
	return BackendRef(p.Struct()), err
}

type TlsPolicy capnp.Struct

// TlsPolicy_TypeID is the unique identifier for the type TlsPolicy.
const TlsPolicy_TypeID = 0xfba0e6ab81a6f86c

func NewTlsPolicy(s *capnp.Segment) (TlsPolicy, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return TlsPolicy(st), err
}

func NewRootTlsPolicy(s *capnp.Segment) (TlsPolicy, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return TlsPolicy(st), err
}

func ReadRootTlsPolicy(msg *capnp.Message) (TlsPolicy, error) {
	root, err := msg.Root()
	return TlsPolicy(root.Struct()), err
}

func (s TlsPolicy) String() string {
	str, _ := text.Marshal(0xfba0e6ab81a6f86c, capnp.Struct(s))
	return str
}

func (s TlsPolicy) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TlsPolicy) DecodeFromPtr(p capnp.Ptr) TlsPolicy {
	return TlsPolicy(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TlsPolicy) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TlsPolicy) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TlsPolicy) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TlsPolicy) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TlsPolicy) Sni() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TlsPolicy) HasSni() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TlsPolicy) SniBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetSni(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TlsPolicy) CertPem() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TlsPolicy) HasCertPem() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TlsPolicy) CertPemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetCertPem(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TlsPolicy) KeyPem() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TlsPolicy) HasKeyPem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TlsPolicy) KeyPemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TlsPolicy) SetKeyPem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TlsPolicy) Kind() TlsPolicy_Kind {
	return TlsPolicy_Kind(capnp.Struct(s).Uint16(0))
}

func (s TlsPolicy) SetKind(v TlsPolicy_Kind) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s TlsPolicy) BackendRef() (BackendRef, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return BackendRef(p.Struct()), err
}

func (s TlsPolicy) HasBackendRef() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TlsPolicy) SetBackendRef(v BackendRef) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewBackendRef sets the backendRef field to a newly
// allocated BackendRef struct, preferring placement in s's segment.
func (s TlsPolicy) NewBackendRef() (BackendRef, error) {
	ss, err := NewBackendRef(capnp.Struct(s).Segment())
	if err != nil {
		return BackendRef{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// TlsPolicy_List is a list of TlsPolicy.
type TlsPolicy_List = capnp.StructList[TlsPolicy]

// NewTlsPolicy creates a new list of TlsPolicy.
func NewTlsPolicy_List(s *capnp.Segment, sz int32) (TlsPolicy_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[TlsPolicy](l), err
}

// TlsPolicy_Future is a wrapper for a TlsPolicy promised by a client call.
type TlsPolicy_Future struct{ *capnp.Future }

func (f TlsPolicy_Future) Struct() (TlsPolicy, error) {
	p, err := f.Future.Ptr()
	return TlsPolicy(p.Struct()), err
}
func (p TlsPolicy_Future) BackendRef() BackendRef_Future {
	return BackendRef_Future{Future: p.Future.Field(3, nil)}
}

type TlsPolicy_Kind uint16

// TlsPolicy_Kind_TypeID is the unique identifier for the type TlsPolicy_Kind.
const TlsPolicy_Kind_TypeID = 0x88ddbc04e9781b3b

// Values of TlsPolicy_Kind.
const (
	TlsPolicy_Kind_tlsPassthrough TlsPolicy_Kind = 0
	TlsPolicy_Kind_tlsTerminate   TlsPolicy_Kind = 1
	TlsPolicy_Kind_https          TlsPolicy_Kind = 2
)

// String returns the enum's constant name.
func (c TlsPolicy_Kind) String() string {
	switch c {
	case TlsPolicy_Kind_tlsPassthrough:
		return "tlsPassthrough"
	case TlsPolicy_Kind_tlsTerminate:
		return "tlsTerminate"
	case TlsPolicy_Kind_https:
		return "https"

	default:
		return ""
	}
}

// TlsPolicy_KindFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TlsPolicy_KindFromString(c string) TlsPolicy_Kind {
	switch c {
	case "tlsPassthrough":
		return TlsPolicy_Kind_tlsPassthrough
	case "tlsTerminate":
		return TlsPolicy_Kind_tlsTerminate
	case "https":
		return TlsPolicy_Kind_https

	default:
		return 0
	}
}

type TlsPolicy_Kind_List = capnp.EnumList[TlsPolicy_Kind]

func NewTlsPolicy_Kind_List(s *capnp.Segment, sz int32) (TlsPolicy_Kind_List, error) {
	return capnp.NewEnumList[TlsPolicy_Kind](s, sz)
}

const schema_c4f4d6e1d8b1a271 = "x\xda\xa4Vkh\x1cU\x14>\xdf\xbd\xb3\x9d\x82\x8d" +
	"\xbb\xc3l\xa9\x0f\x96\xad\xa5\xf8\xa8}\xee\x8ahZ\xd8" +
	"\x1a-\x14#to(>\x82\x82\xd3\xdd\x9b\xee4\xbb" +
	"\xb3\x9b\x9d\x89\xc9FCZL!J\"\x0a\x05\x0d\xa6" +
	"%\x8a--\xa6\xa0`\xa1\x15\x8b\x8a\xb1\x08\xfe\x92\x82" +
	"(\xb4?\x8aZ\xe9\xcf\x16\x0b\x16IG\xee>f\xb7" +
	"1!\x01\x7f\xde\xcb\xe1\x9c\xef~\x8f3\xb3\xf5\x04\xdb" +
	"\xa9mk\xdb\x12\"&v\x84V\xf8\xdb\xef\x1f\xbc\xa6" +
	"}uy\x8c\x8c\x87\x98\x9f\xff\xfb\xc4\xa1O\xafN\xff" +
	"C\x84\xe40\xdb\x07\xf3=\xa6\x13\x99\x13l\x0fan" +
	"\xe4\xfc\xf6\x1f\xc7\xce\xbem\xc4\xe0\xf7}\xfc\xf9/W" +
	"~\xfek\x96B\xd0\x89\x92\xa7\xd8:\x98\xe7\xaa\xa5g" +
	"X\x8a\xe0\x9f<\x9c\xbc\xd1\xf9\xdb\xceI\x121\xfc\xa7" +
	"\xfa\x0f\xd6\x01\xf3f\xb5\xfa:\x1b \xf8\x8f\x0f\xbd\x7f" +
	"k\xfb\x97\xaf\x7fDw\xb6V\x15I\xc17\xc0\xb4\xb8" +
	"*~\x85\xab\xe2u\xe3O>3[Y{|^\xeb" +
	"]\xd09\x90\xfc\x96'`\xfe\xc4\xd7\x10\x99\xbf\xf2?" +
	"\x09\xfe\xae\xd5W.\xfd\xfe\xce\xd4\xf7\xb4\x00\xec\xd3\xda" +
	"}0\xcfk\xaa\xf79M\xc1^{qvgh\xe3" +
	"\x87\x17\x16\x02rMK\xc0\xbcU-\xbe\xa9) W" +
	"\x8fM\x1d\xbb\xeb\xcd\xd1\x1f\xc8x\x905Q\x11\x92v" +
	"\xa8\x1b\xe6pHUVB{\x08\xfe\xf4\xcc\x91\x8b7" +
	"^L\\\x9a\x0f\x99\xeb\x9c(9\x11\xea\x80yT\x95" +
	"''C/\x80\xe0?\xf0\xdd\xd7\xdd\x8f^8xy" +
	"!\x18\xd7W$`BW\xcd\xe7V(\x18\x81d\xf3" +
	"\xa8VH\x93/\xe9\xed0m}\x0dQ\xb2O\x8f\x83" +
	"6\xf9\xb6\xb3\xbf,]w\x8b\xe6fr\xb2`m\xa9" +
	"\x9f7g\xac\x92Sj\xdf\x9bw\xd3\xc5\xbc\x9d\xa9l" +
	"\xee\xd4m'\x9b\x06\xc4*0\"#6D\x04\x18\xf7" +
	"\x1e \x023V'\x88|/\xef\xa6-\xd7\xf5(\x95" +
	"+\x17\xfb\xf7\xe7\xd4\xc5^Y.\xd8\x14v,O\xc6" +
	"s\x9eWr\x83y|\xc1y\xbb\xa5\xa5geY\xcd" +
	"\xd1\xb8F\xa4\x81\xc8hK\x10\x89\x95\x1cb=C\xdc" +
	"\xf6d\xc1\xc5\xdd\x844\x07\"Mj\x08\xear\x89\xe7" +
	"tX\x99^\xe9d\xbbd\x0f\xa9\x11+\x83\x11\x8f<" +
	"K$\x1e\xe6\x10\x8f1\x00Q\xa8\xbbm\x1b\x88\xc4F" +
	"\x0e\xf1\x04\x83\x9f+\xba\x9ec\x15$\x11a\x151\xac" +
	"\"\x84K\xc5\xb2\x07\x9d\x18\xf4\x96\xc1|1\x1e\xc3\xdd" +
	"EG.>\xd5\x08\xc6v\x11\x89\xad\x1cb\xc7\xc2c" +
	"\xab<+M\x08\x15DZ\x13\x8a\xc8\x928\xd2\x96\x17" +
	"\xcf\xa9\x86BC\xabc\xb1!\xdci;Y\x11\x09\xb0" +
	"Y\xea\xf5/s\x88\x1cC\x1b|\xbf\x06N*)^" +
	"\xe5\x10y\x866v\xdb\x8fV\xcd`\xb7\x13\x89,\x87" +
	"(1\xb4\xf19?\x0aNd\x14Tm\x8eCx\x0c" +
	"\xe1^\xdb\xc9\"\xdc\x9cH@\x98\x10\x97\x83V\xc6k" +
	"\xbc,U*\xcb\x1e{\xb0q\x8c\x97\xe5~\x19\x9c\x96" +
	"x\x98\xe8\x97\xbc\\\xf9\xff\xbeY\xc4\x96\x9e\x17/-" +
	"W\xbf\x03u\xfd\x9e[D?\x95\x03% \x853\xb6" +
	"l\x81\x14l\x85eY9myU!7w\xda\xfc" +
	"\x8e`&\xaa\xc1\\\xdd^\x0d\xa6\xa2\xa0Fr\x9d\xdc" +
	"\x1a\xa9K\xf4\xde]G\x98\xa9TcrO\xf0\xe0\xc9" +
	"\x0e\"q\x84CL3\xc4\xe0\xfb\xf5'\x1fU<L" +
	"q\x88\x93\x0c1v[]+(\xc7\x15\xff\xd3\x1cb" +
	"\x86!\xc6\xe7\xd4\xb5\xf2\xc5)\xe5\x96O8\xc4g\x0c" +
	"\x86\xc6\xa2\xd0\x88\x8c\xd3\xddDb\x86C\x9ce0B" +
	"\x91(BD\xc6\x99!\"\xf1\x05\x87\xf8\x86ad_" +
	"-\xbb\x01\x8d\xa5:\x01\x8a\xdaH\xeb\xbeU1\x88\xf7" +
	"\xf5\xcb\xb2\x8aG\xb0\xeek\xf7\xa9\x9c\xb4\xb2\xb2\x8cH" +
	"\xe3\xe3UOM\x8f=\xf8t\xd1\xf1$q'\xb0\xa3" +
	"o\xe5\xf3\xc5\x81.k\x80ROe2\xd2u\x01b" +
	"\xc0\x92f\xe9\x94\x95\xf8\xf3V\xbe\x7f\xbeY\xd6\x11\x89" +
	"\xf5\x1cbk\x8bY6%\x9a\x0e\xd2{e%\xf0\xfe" +
	"k\xaa\xc12\xbd\xbf7\xef\xa6jrUS\xdd\xfc\x80" +
	"7R\x1d\x0d@\x0c+\x10\x83\x1cb\xb4\x05\xc4!\xa5" +
	"\xea\x1b\x1cb\x8c\xc1`\xac&\xdea\xa5\xd2A\x0e1" +
	"\xce\x00^S\xee-\xb5\x13F9\xc4\xbbJ9^S" +
	"nB)7\xce!>`\xd0]\xc7n\x80\x1e\xc9\xc8" +
	"\xb2\x97\x96\x85 \xdd\xbd\xb2\xd2rll\x84\x00mm" +
	"#\xf8u\x99\xbb\x88\xcb\x1eD\x9a?\x0e5\xa1\xfe\x0d" +
	"\x00\x00\xff\xff\x92\xaaZ-"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c4f4d6e1d8b1a271,
		Nodes: []uint64{
			0x88ddbc04e9781b3b,
			0x8ab888cb3bbd007f,
			0x9940e34bf23385a8,
			0xa17bba3bf9977a36,
			0xa52079c444398c22,
			0xc59c8ee4dce11545,
			0xc69b2c0540c4d320,
			0xc884830b9e9c9ee6,
			0xdc3258f2d394aca0,
			0xdd80c62b5abfc321,
			0xfba0e6ab81a6f86c,
		},
		Compressed: true,
	})
}
