// Code generated by capnpc-go. DO NOT EDIT.

package dns

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type RecordType uint16

// RecordType_TypeID is the unique identifier for the type RecordType.
const RecordType_TypeID = 0xad3cf7360a023d1c

// Values of RecordType.
const (
	RecordType_a     RecordType = 0
	RecordType_aaaa  RecordType = 1
	RecordType_cname RecordType = 2
	RecordType_mx    RecordType = 3
	RecordType_ns    RecordType = 4
	RecordType_ptr   RecordType = 5
	RecordType_soa   RecordType = 6
	RecordType_txt   RecordType = 7
)

// String returns the enum's constant name.
func (c RecordType) String() string {
	switch c {
	case RecordType_a:
		return "a"
	case RecordType_aaaa:
		return "aaaa"
	case RecordType_cname:
		return "cname"
	case RecordType_mx:
		return "mx"
	case RecordType_ns:
		return "ns"
	case RecordType_ptr:
		return "ptr"
	case RecordType_soa:
		return "soa"
	case RecordType_txt:
		return "txt"

	default:
		return ""
	}
}

// RecordTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RecordTypeFromString(c string) RecordType {
	switch c {
	case "a":
		return RecordType_a
	case "aaaa":
		return RecordType_aaaa
	case "cname":
		return RecordType_cname
	case "mx":
		return RecordType_mx
	case "ns":
		return RecordType_ns
	case "ptr":
		return RecordType_ptr
	case "soa":
		return RecordType_soa
	case "txt":
		return RecordType_txt

	default:
		return 0
	}
}

type RecordType_List = capnp.EnumList[RecordType]

func NewRecordType_List(s *capnp.Segment, sz int32) (RecordType_List, error) {
	return capnp.NewEnumList[RecordType](s, sz)
}

type ARecord capnp.Struct

// ARecord_TypeID is the unique identifier for the type ARecord.
const ARecord_TypeID = 0xe2cd6a34396bf6fa

func NewARecord(s *capnp.Segment) (ARecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ARecord(st), err
}

func NewRootARecord(s *capnp.Segment) (ARecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ARecord(st), err
}

func ReadRootARecord(msg *capnp.Message) (ARecord, error) {
	root, err := msg.Root()
	return ARecord(root.Struct()), err
}

func (s ARecord) String() string {
	str, _ := text.Marshal(0xe2cd6a34396bf6fa, capnp.Struct(s))
	return str
}

func (s ARecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ARecord) DecodeFromPtr(p capnp.Ptr) ARecord {
	return ARecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ARecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ARecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ARecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ARecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ARecord) Address() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s ARecord) SetAddress(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// ARecord_List is a list of ARecord.
type ARecord_List = capnp.StructList[ARecord]

// NewARecord creates a new list of ARecord.
func NewARecord_List(s *capnp.Segment, sz int32) (ARecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[ARecord](l), err
}

// ARecord_Future is a wrapper for a ARecord promised by a client call.
type ARecord_Future struct{ *capnp.Future }

func (f ARecord_Future) Struct() (ARecord, error) {
	p, err := f.Future.Ptr()
	return ARecord(p.Struct()), err
}

type AAAARecord capnp.Struct

// AAAARecord_TypeID is the unique identifier for the type AAAARecord.
const AAAARecord_TypeID = 0x9e02a71670b20379

func NewAAAARecord(s *capnp.Segment) (AAAARecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return AAAARecord(st), err
}

func NewRootAAAARecord(s *capnp.Segment) (AAAARecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return AAAARecord(st), err
}

func ReadRootAAAARecord(msg *capnp.Message) (AAAARecord, error) {
	root, err := msg.Root()
	return AAAARecord(root.Struct()), err
}

func (s AAAARecord) String() string {
	str, _ := text.Marshal(0x9e02a71670b20379, capnp.Struct(s))
	return str
}

func (s AAAARecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AAAARecord) DecodeFromPtr(p capnp.Ptr) AAAARecord {
	return AAAARecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AAAARecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AAAARecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AAAARecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AAAARecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AAAARecord) AddressHigh() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s AAAARecord) SetAddressHigh(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s AAAARecord) AddressLow() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s AAAARecord) SetAddressLow(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// AAAARecord_List is a list of AAAARecord.
type AAAARecord_List = capnp.StructList[AAAARecord]

// NewAAAARecord creates a new list of AAAARecord.
func NewAAAARecord_List(s *capnp.Segment, sz int32) (AAAARecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[AAAARecord](l), err
}

// AAAARecord_Future is a wrapper for a AAAARecord promised by a client call.
type AAAARecord_Future struct{ *capnp.Future }

func (f AAAARecord_Future) Struct() (AAAARecord, error) {
	p, err := f.Future.Ptr()
	return AAAARecord(p.Struct()), err
}

type CNAMERecord capnp.Struct

// CNAMERecord_TypeID is the unique identifier for the type CNAMERecord.
const CNAMERecord_TypeID = 0xbe7ec061ddbdd224

func NewCNAMERecord(s *capnp.Segment) (CNAMERecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CNAMERecord(st), err
}

func NewRootCNAMERecord(s *capnp.Segment) (CNAMERecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CNAMERecord(st), err
}

func ReadRootCNAMERecord(msg *capnp.Message) (CNAMERecord, error) {
	root, err := msg.Root()
	return CNAMERecord(root.Struct()), err
}

func (s CNAMERecord) String() string {
	str, _ := text.Marshal(0xbe7ec061ddbdd224, capnp.Struct(s))
	return str
}

func (s CNAMERecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CNAMERecord) DecodeFromPtr(p capnp.Ptr) CNAMERecord {
	return CNAMERecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CNAMERecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CNAMERecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CNAMERecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CNAMERecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CNAMERecord) Host() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CNAMERecord) HasHost() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CNAMERecord) HostBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CNAMERecord) SetHost(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// CNAMERecord_List is a list of CNAMERecord.
type CNAMERecord_List = capnp.StructList[CNAMERecord]

// NewCNAMERecord creates a new list of CNAMERecord.
func NewCNAMERecord_List(s *capnp.Segment, sz int32) (CNAMERecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CNAMERecord](l), err
}

// CNAMERecord_Future is a wrapper for a CNAMERecord promised by a client call.
type CNAMERecord_Future struct{ *capnp.Future }

func (f CNAMERecord_Future) Struct() (CNAMERecord, error) {
	p, err := f.Future.Ptr()
	return CNAMERecord(p.Struct()), err
}

type MXRecord capnp.Struct

// MXRecord_TypeID is the unique identifier for the type MXRecord.
const MXRecord_TypeID = 0x8e0d32b60a612eb9

func NewMXRecord(s *capnp.Segment) (MXRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MXRecord(st), err
}

func NewRootMXRecord(s *capnp.Segment) (MXRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return MXRecord(st), err
}

func ReadRootMXRecord(msg *capnp.Message) (MXRecord, error) {
	root, err := msg.Root()
	return MXRecord(root.Struct()), err
}

func (s MXRecord) String() string {
	str, _ := text.Marshal(0x8e0d32b60a612eb9, capnp.Struct(s))
	return str
}

func (s MXRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MXRecord) DecodeFromPtr(p capnp.Ptr) MXRecord {
	return MXRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MXRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MXRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MXRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MXRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MXRecord) Preference() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s MXRecord) SetPreference(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

func (s MXRecord) Exchange() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MXRecord) HasExchange() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MXRecord) ExchangeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MXRecord) SetExchange(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// MXRecord_List is a list of MXRecord.
type MXRecord_List = capnp.StructList[MXRecord]

// NewMXRecord creates a new list of MXRecord.
func NewMXRecord_List(s *capnp.Segment, sz int32) (MXRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[MXRecord](l), err
}

// MXRecord_Future is a wrapper for a MXRecord promised by a client call.
type MXRecord_Future struct{ *capnp.Future }

func (f MXRecord_Future) Struct() (MXRecord, error) {
	p, err := f.Future.Ptr()
	return MXRecord(p.Struct()), err
}

type NSRecord capnp.Struct

// NSRecord_TypeID is the unique identifier for the type NSRecord.
const NSRecord_TypeID = 0x931072c4a18d0c61

func NewNSRecord(s *capnp.Segment) (NSRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return NSRecord(st), err
}

func NewRootNSRecord(s *capnp.Segment) (NSRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return NSRecord(st), err
}

func ReadRootNSRecord(msg *capnp.Message) (NSRecord, error) {
	root, err := msg.Root()
	return NSRecord(root.Struct()), err
}

func (s NSRecord) String() string {
	str, _ := text.Marshal(0x931072c4a18d0c61, capnp.Struct(s))
	return str
}

func (s NSRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NSRecord) DecodeFromPtr(p capnp.Ptr) NSRecord {
	return NSRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NSRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NSRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NSRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NSRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NSRecord) Host() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s NSRecord) HasHost() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NSRecord) HostBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s NSRecord) SetHost(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// NSRecord_List is a list of NSRecord.
type NSRecord_List = capnp.StructList[NSRecord]

// NewNSRecord creates a new list of NSRecord.
func NewNSRecord_List(s *capnp.Segment, sz int32) (NSRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[NSRecord](l), err
}

// NSRecord_Future is a wrapper for a NSRecord promised by a client call.
type NSRecord_Future struct{ *capnp.Future }

func (f NSRecord_Future) Struct() (NSRecord, error) {
	p, err := f.Future.Ptr()
	return NSRecord(p.Struct()), err
}

type PTRRecord capnp.Struct

// PTRRecord_TypeID is the unique identifier for the type PTRRecord.
const PTRRecord_TypeID = 0xabf03d4c5c6a2ede

func NewPTRRecord(s *capnp.Segment) (PTRRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PTRRecord(st), err
}

func NewRootPTRRecord(s *capnp.Segment) (PTRRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return PTRRecord(st), err
}

func ReadRootPTRRecord(msg *capnp.Message) (PTRRecord, error) {
	root, err := msg.Root()
	return PTRRecord(root.Struct()), err
}

func (s PTRRecord) String() string {
	str, _ := text.Marshal(0xabf03d4c5c6a2ede, capnp.Struct(s))
	return str
}

func (s PTRRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PTRRecord) DecodeFromPtr(p capnp.Ptr) PTRRecord {
	return PTRRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PTRRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PTRRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PTRRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PTRRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PTRRecord) Host() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PTRRecord) HasHost() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PTRRecord) HostBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PTRRecord) SetHost(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// PTRRecord_List is a list of PTRRecord.
type PTRRecord_List = capnp.StructList[PTRRecord]

// NewPTRRecord creates a new list of PTRRecord.
func NewPTRRecord_List(s *capnp.Segment, sz int32) (PTRRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[PTRRecord](l), err
}

// PTRRecord_Future is a wrapper for a PTRRecord promised by a client call.
type PTRRecord_Future struct{ *capnp.Future }

func (f PTRRecord_Future) Struct() (PTRRecord, error) {
	p, err := f.Future.Ptr()
	return PTRRecord(p.Struct()), err
}

type SOARecord capnp.Struct

// SOARecord_TypeID is the unique identifier for the type SOARecord.
const SOARecord_TypeID = 0xf4dd868f57c8848a

func NewSOARecord(s *capnp.Segment) (SOARecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return SOARecord(st), err
}

func NewRootSOARecord(s *capnp.Segment) (SOARecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return SOARecord(st), err
}

func ReadRootSOARecord(msg *capnp.Message) (SOARecord, error) {
	root, err := msg.Root()
	return SOARecord(root.Struct()), err
}

func (s SOARecord) String() string {
	str, _ := text.Marshal(0xf4dd868f57c8848a, capnp.Struct(s))
	return str
}

func (s SOARecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SOARecord) DecodeFromPtr(p capnp.Ptr) SOARecord {
	return SOARecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SOARecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SOARecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SOARecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SOARecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SOARecord) Mname() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SOARecord) HasMname() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SOARecord) MnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SOARecord) SetMname(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s SOARecord) Rname() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SOARecord) HasRname() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SOARecord) RnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SOARecord) SetRname(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s SOARecord) Serial() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s SOARecord) SetSerial(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s SOARecord) Refresh() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s SOARecord) SetRefresh(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s SOARecord) Retry() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s SOARecord) SetRetry(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s SOARecord) Expire() uint32 {
	return capnp.Struct(s).Uint32(12)
}

func (s SOARecord) SetExpire(v uint32) {
	capnp.Struct(s).SetUint32(12, v)
}

func (s SOARecord) Minimum() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s SOARecord) SetMinimum(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

// SOARecord_List is a list of SOARecord.
type SOARecord_List = capnp.StructList[SOARecord]

// NewSOARecord creates a new list of SOARecord.
func NewSOARecord_List(s *capnp.Segment, sz int32) (SOARecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2}, sz)
	return capnp.StructList[SOARecord](l), err
}

// SOARecord_Future is a wrapper for a SOARecord promised by a client call.
type SOARecord_Future struct{ *capnp.Future }

func (f SOARecord_Future) Struct() (SOARecord, error) {
	p, err := f.Future.Ptr()
	return SOARecord(p.Struct()), err
}

type TXTRecord capnp.Struct

// TXTRecord_TypeID is the unique identifier for the type TXTRecord.
const TXTRecord_TypeID = 0xfb6ecb8857844d67

func NewTXTRecord(s *capnp.Segment) (TXTRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return TXTRecord(st), err
}

func NewRootTXTRecord(s *capnp.Segment) (TXTRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return TXTRecord(st), err
}

func ReadRootTXTRecord(msg *capnp.Message) (TXTRecord, error) {
	root, err := msg.Root()
	return TXTRecord(root.Struct()), err
}

func (s TXTRecord) String() string {
	str, _ := text.Marshal(0xfb6ecb8857844d67, capnp.Struct(s))
	return str
}

func (s TXTRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TXTRecord) DecodeFromPtr(p capnp.Ptr) TXTRecord {
	return TXTRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TXTRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TXTRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TXTRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TXTRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TXTRecord) Values() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s TXTRecord) HasValues() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TXTRecord) SetValues(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewValues sets the values field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s TXTRecord) NewValues(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// TXTRecord_List is a list of TXTRecord.
type TXTRecord_List = capnp.StructList[TXTRecord]

// NewTXTRecord creates a new list of TXTRecord.
func NewTXTRecord_List(s *capnp.Segment, sz int32) (TXTRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[TXTRecord](l), err
}

// TXTRecord_Future is a wrapper for a TXTRecord promised by a client call.
type TXTRecord_Future struct{ *capnp.Future }

func (f TXTRecord_Future) Struct() (TXTRecord, error) {
	p, err := f.Future.Ptr()
	return TXTRecord(p.Struct()), err
}

type DnsRecord capnp.Struct
type DnsRecord_Which uint16

const (
	DnsRecord_Which_a     DnsRecord_Which = 0
	DnsRecord_Which_aaaa  DnsRecord_Which = 1
	DnsRecord_Which_cname DnsRecord_Which = 2
	DnsRecord_Which_mx    DnsRecord_Which = 3
	DnsRecord_Which_ns    DnsRecord_Which = 4
	DnsRecord_Which_ptr   DnsRecord_Which = 5
	DnsRecord_Which_soa   DnsRecord_Which = 6
	DnsRecord_Which_txt   DnsRecord_Which = 7
)

func (w DnsRecord_Which) String() string {
	const s = "aaaaacnamemxnsptrsoatxt"
	switch w {
	case DnsRecord_Which_a:
		return s[0:1]
	case DnsRecord_Which_aaaa:
		return s[1:5]
	case DnsRecord_Which_cname:
		return s[5:10]
	case DnsRecord_Which_mx:
		return s[10:12]
	case DnsRecord_Which_ns:
		return s[12:14]
	case DnsRecord_Which_ptr:
		return s[14:17]
	case DnsRecord_Which_soa:
		return s[17:20]
	case DnsRecord_Which_txt:
		return s[20:23]

	}
	return "DnsRecord_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// DnsRecord_TypeID is the unique identifier for the type DnsRecord.
const DnsRecord_TypeID = 0x9680f086587268f3

func NewDnsRecord(s *capnp.Segment) (DnsRecord, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return DnsRecord(st), err
}

func NewRootDnsRecord(s *capnp.Segment) (DnsRecord, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return DnsRecord(st), err
}

func ReadRootDnsRecord(msg *capnp.Message) (DnsRecord, error) {
	root, err := msg.Root()
	return DnsRecord(root.Struct()), err
}

func (s DnsRecord) String() string {
	str, _ := text.Marshal(0x9680f086587268f3, capnp.Struct(s))
	return str
}

func (s DnsRecord) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DnsRecord) DecodeFromPtr(p capnp.Ptr) DnsRecord {
	return DnsRecord(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DnsRecord) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s DnsRecord) Which() DnsRecord_Which {
	return DnsRecord_Which(capnp.Struct(s).Uint16(6))
}
func (s DnsRecord) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DnsRecord) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DnsRecord) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DnsRecord) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s DnsRecord) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DnsRecord) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s DnsRecord) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s DnsRecord) Ttl() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s DnsRecord) SetTtl(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s DnsRecord) Type() RecordType {
	return RecordType(capnp.Struct(s).Uint16(4))
}

func (s DnsRecord) SetType(v RecordType) {
	capnp.Struct(s).SetUint16(4, uint16(v))
}

func (s DnsRecord) A() (ARecord, error) {
	if capnp.Struct(s).Uint16(6) != 0 {
		panic("Which() != a")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return ARecord(p.Struct()), err
}

func (s DnsRecord) HasA() bool {
	if capnp.Struct(s).Uint16(6) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetA(v ARecord) error {
	capnp.Struct(s).SetUint16(6, 0)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewA sets the a field to a newly
// allocated ARecord struct, preferring placement in s's segment.
func (s DnsRecord) NewA() (ARecord, error) {
	capnp.Struct(s).SetUint16(6, 0)
	ss, err := NewARecord(capnp.Struct(s).Segment())
	if err != nil {
		return ARecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Aaaa() (AAAARecord, error) {
	if capnp.Struct(s).Uint16(6) != 1 {
		panic("Which() != aaaa")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return AAAARecord(p.Struct()), err
}

func (s DnsRecord) HasAaaa() bool {
	if capnp.Struct(s).Uint16(6) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetAaaa(v AAAARecord) error {
	capnp.Struct(s).SetUint16(6, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewAaaa sets the aaaa field to a newly
// allocated AAAARecord struct, preferring placement in s's segment.
func (s DnsRecord) NewAaaa() (AAAARecord, error) {
	capnp.Struct(s).SetUint16(6, 1)
	ss, err := NewAAAARecord(capnp.Struct(s).Segment())
	if err != nil {
		return AAAARecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Cname() (CNAMERecord, error) {
	if capnp.Struct(s).Uint16(6) != 2 {
		panic("Which() != cname")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return CNAMERecord(p.Struct()), err
}

func (s DnsRecord) HasCname() bool {
	if capnp.Struct(s).Uint16(6) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetCname(v CNAMERecord) error {
	capnp.Struct(s).SetUint16(6, 2)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewCname sets the cname field to a newly
// allocated CNAMERecord struct, preferring placement in s's segment.
func (s DnsRecord) NewCname() (CNAMERecord, error) {
	capnp.Struct(s).SetUint16(6, 2)
	ss, err := NewCNAMERecord(capnp.Struct(s).Segment())
	if err != nil {
		return CNAMERecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Mx() (MXRecord, error) {
	if capnp.Struct(s).Uint16(6) != 3 {
		panic("Which() != mx")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return MXRecord(p.Struct()), err
}

func (s DnsRecord) HasMx() bool {
	if capnp.Struct(s).Uint16(6) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetMx(v MXRecord) error {
	capnp.Struct(s).SetUint16(6, 3)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewMx sets the mx field to a newly
// allocated MXRecord struct, preferring placement in s's segment.
func (s DnsRecord) NewMx() (MXRecord, error) {
	capnp.Struct(s).SetUint16(6, 3)
	ss, err := NewMXRecord(capnp.Struct(s).Segment())
	if err != nil {
		return MXRecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Ns() (NSRecord, error) {
	if capnp.Struct(s).Uint16(6) != 4 {
		panic("Which() != ns")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return NSRecord(p.Struct()), err
}

func (s DnsRecord) HasNs() bool {
	if capnp.Struct(s).Uint16(6) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetNs(v NSRecord) error {
	capnp.Struct(s).SetUint16(6, 4)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewNs sets the ns field to a newly
// allocated NSRecord struct, preferring placement in s's segment.
func (s DnsRecord) NewNs() (NSRecord, error) {
	capnp.Struct(s).SetUint16(6, 4)
	ss, err := NewNSRecord(capnp.Struct(s).Segment())
	if err != nil {
		return NSRecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Ptr() (PTRRecord, error) {
	if capnp.Struct(s).Uint16(6) != 5 {
		panic("Which() != ptr")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return PTRRecord(p.Struct()), err
}

func (s DnsRecord) HasPtr() bool {
	if capnp.Struct(s).Uint16(6) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetPtr(v PTRRecord) error {
	capnp.Struct(s).SetUint16(6, 5)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPtr sets the ptr field to a newly
// allocated PTRRecord struct, preferring placement in s's segment.
func (s DnsRecord) NewPtr() (PTRRecord, error) {
	capnp.Struct(s).SetUint16(6, 5)
	ss, err := NewPTRRecord(capnp.Struct(s).Segment())
	if err != nil {
		return PTRRecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Soa() (SOARecord, error) {
	if capnp.Struct(s).Uint16(6) != 6 {
		panic("Which() != soa")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return SOARecord(p.Struct()), err
}

func (s DnsRecord) HasSoa() bool {
	if capnp.Struct(s).Uint16(6) != 6 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetSoa(v SOARecord) error {
	capnp.Struct(s).SetUint16(6, 6)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewSoa sets the soa field to a newly
// allocated SOARecord struct, preferring placement in s's segment.
func (s DnsRecord) NewSoa() (SOARecord, error) {
	capnp.Struct(s).SetUint16(6, 6)
	ss, err := NewSOARecord(capnp.Struct(s).Segment())
	if err != nil {
		return SOARecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s DnsRecord) Txt() (TXTRecord, error) {
	if capnp.Struct(s).Uint16(6) != 7 {
		panic("Which() != txt")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return TXTRecord(p.Struct()), err
}

func (s DnsRecord) HasTxt() bool {
	if capnp.Struct(s).Uint16(6) != 7 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s DnsRecord) SetTxt(v TXTRecord) error {
	capnp.Struct(s).SetUint16(6, 7)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewTxt sets the txt field to a newly
// allocated TXTRecord struct, preferring placement in s's segment.
func (s DnsRecord) NewTxt() (TXTRecord, error) {
	capnp.Struct(s).SetUint16(6, 7)
	ss, err := NewTXTRecord(capnp.Struct(s).Segment())
	if err != nil {
		return TXTRecord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// DnsRecord_List is a list of DnsRecord.
type DnsRecord_List = capnp.StructList[DnsRecord]

// NewDnsRecord creates a new list of DnsRecord.
func NewDnsRecord_List(s *capnp.Segment, sz int32) (DnsRecord_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[DnsRecord](l), err
}

// DnsRecord_Future is a wrapper for a DnsRecord promised by a client call.
type DnsRecord_Future struct{ *capnp.Future }

func (f DnsRecord_Future) Struct() (DnsRecord, error) {
	p, err := f.Future.Ptr()
	return DnsRecord(p.Struct()), err
}
func (p DnsRecord_Future) A() ARecord_Future {
	return ARecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Aaaa() AAAARecord_Future {
	return AAAARecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Cname() CNAMERecord_Future {
	return CNAMERecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Mx() MXRecord_Future {
	return MXRecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Ns() NSRecord_Future {
	return NSRecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Ptr() PTRRecord_Future {
	return PTRRecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Soa() SOARecord_Future {
	return SOARecord_Future{Future: p.Future.Field(1, nil)}
}
func (p DnsRecord_Future) Txt() TXTRecord_Future {
	return TXTRecord_Future{Future: p.Future.Field(1, nil)}
}

type Zone capnp.Struct

// Zone_TypeID is the unique identifier for the type Zone.
const Zone_TypeID = 0xe331a55c5a959108

func NewZone(s *capnp.Segment) (Zone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 9})
	return Zone(st), err
}

func NewRootZone(s *capnp.Segment) (Zone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 9})
	return Zone(st), err
}

func ReadRootZone(msg *capnp.Message) (Zone, error) {
	root, err := msg.Root()
	return Zone(root.Struct()), err
}

func (s Zone) String() string {
	str, _ := text.Marshal(0xe331a55c5a959108, capnp.Struct(s))
	return str
}

func (s Zone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Zone) DecodeFromPtr(p capnp.Ptr) Zone {
	return Zone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Zone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Zone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Zone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Zone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Zone) Records() (DnsRecord_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return DnsRecord_List(p.List()), err
}

func (s Zone) HasRecords() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Zone) SetRecords(v DnsRecord_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewRecords sets the records field to a newly
// allocated DnsRecord_List, preferring placement in s's segment.
func (s Zone) NewRecords(n int32) (DnsRecord_List, error) {
	l, err := NewDnsRecord_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return DnsRecord_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Zone) AIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasAIndexes() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Zone) SetAIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewAIndexes sets the aIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewAIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Zone) AaaaIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasAaaaIndexes() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Zone) SetAaaaIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewAaaaIndexes sets the aaaaIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewAaaaIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Zone) CnameIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasCnameIndexes() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Zone) SetCnameIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewCnameIndexes sets the cnameIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewCnameIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s Zone) MxIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasMxIndexes() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Zone) SetMxIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewMxIndexes sets the mxIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewMxIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}
func (s Zone) NsIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasNsIndexes() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Zone) SetNsIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewNsIndexes sets the nsIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewNsIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s Zone) PtrIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasPtrIndexes() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Zone) SetPtrIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewPtrIndexes sets the ptrIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewPtrIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}
func (s Zone) SoaIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasSoaIndexes() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Zone) SetSoaIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewSoaIndexes sets the soaIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewSoaIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}
func (s Zone) TxtIndexes() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return capnp.UInt32List(p.List()), err
}

func (s Zone) HasTxtIndexes() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Zone) SetTxtIndexes(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(8, v.ToPtr())
}

// NewTxtIndexes sets the txtIndexes field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s Zone) NewTxtIndexes(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(8, l.ToPtr())
	return l, err
}

// Zone_List is a list of Zone.
type Zone_List = capnp.StructList[Zone]

// NewZone creates a new list of Zone.
func NewZone_List(s *capnp.Segment, sz int32) (Zone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 9}, sz)
	return capnp.StructList[Zone](l), err
}

// Zone_Future is a wrapper for a Zone promised by a client call.
type Zone_Future struct{ *capnp.Future }

func (f Zone_Future) Struct() (Zone, error) {
	p, err := f.Future.Ptr()
	return Zone(p.Struct()), err
}

const schema_d8c6e9d1a4b2f307 = "x\xda\x9cU]l\x14U\x14>\xe7\xde\x9d\x99\xdd\xa5" +
	"uw\xb8\xd5\x08\xc1\x14IM\x80\x00\xb6\xa5\x1ahJ" +
	"\xca*$\x94P\xec\xec6\x01\x1b\x1e\x1cv/\xb4\xc8" +
	"\xce\xae3\x8b\xec\x1a\x11I\x80\xa8\x09\"\xfe=\x90h" +
	"B#QQ\x13C\xd4H\x02\x06\x92\xa2\x18%Q\xe3" +
	"\x83/\xf8\xa01\x91\x07\x12\x0c\xfe\x828\xe6\xdc\xe9\xce" +
	"L\xda\xf2\xa0O;\xf3}\xe7\x9c{\xe6\x9c\xef\xbb\xdb" +
	"i\xf1\xd5\x89\xae\xd6{5`V\x9f\xa6\xfb\xa7\x96\xd9" +
	"\xe9\x8f\xba[\x9f\x07+\x8d\xe8\x1b\xd7N\xbe\xf1\xf5\xe5" +
	"O\xbf\x03\x0d\x0d\x00\xb1\x87\x1d\x15\x07\x18=\xedc\xbb" +
	"\x01}\xbb\xe5\xd0\xb1\x097\xfb\x12\x98\xe9i\xb1?\xb1" +
	"\xa3\xe2\x8a\x8a\xbd\xcc\xfa\x01\xfdk\xa3\xee\xe6\x83W\x9f" +
	"~uJ\xe1\xb5\xccH\"\x17)>.Ln\x00," +
	"o\xe5\x15\x06\xe87\xf8\xc9\xea\x1do\xb2\xd7)\x9cE" +
	"\xe1\x09*x@;!\x0ei\xf4\xf4\xacFm|\xbf" +
	"l\xc7\x96\x0d\xab\xae\xbe3S\x1bW\xb4q\xf1\x9b\x8a" +
	"\xfdE\xa36\xe6\xadb\xe9\xfb\xff\xe8{\x0f\xcct\xac" +
	",\xa00\xf5\x13b\x8eN\x81\xb7\xeb\x9f\x01\xfa\x1d\xdf" +
	"\x9c\xb9d\x9f}\xea\x93\x99\x8a6\xf4\x93b\x9f\x8a\xdd" +
	"\xa3S\xd1\xeb\xbf?\xba\xb2g\xc7\xc5\x1f\xa6|\x9bj" +
	"\xf65\xfdEq\\\xc5\x1eS\xb1\xc9#\xaf\x8cl9" +
	"\xde\xf5\xe3\x94\xba)\x8a8\xa7?!\xceS\xec\xf2s" +
	"\xba\x8f\x80\xfes\xfb/l:|\xf0\xd2\xafT\x98\xc7" +
	"\xa2\xd5\\\x1fK\x8d\x8b\x06\xe5-\xdf\x95:L\xd1\xdb" +
	"\x07\xf7oz\xe6\x0b\xe7\xc6L-\xdfL\x8f\x0bm\x16" +
	"=\xe1\xac~X\xea\x97\x1coY\xd1\xae:X\xed\x1d" +
	"\xdc\x9c\x97\xc5\x0awKC\x88V\x92'\x00\x12\x08`" +
	".\x1a\x01\xb0\x16r\xb4z\x18\"\xb6!a]\xeb\x01" +
	"\xacN\x8eV\x1fC\xbf\xea\xcam\xd2\x95\x0e\xf0\xa2D" +
	"\x03\x18\x1a\x80\xbe\xac\x17Gmg\xbb\x04\x00l\x01\x86" +
	"-\x80\xf1\xb36\x16bg%\xc2\xb3Z\x17\x03XI" +
	"\x8eV\x1b\xc3\xcch\xc5\xab\xcd\x94\xbb\xc6\xf1\xf2\xb2h" +
	"T\x82\xe4%\xcddq\x0f.\x06(\xccG\x8e\x85%" +
	"\x18\xf6*\x16\xe1\x02\x80B\x07\xc1\x9d\xc8\xd0d\xac\x0d" +
	"\x19\x80X\xaa\xc2\x17\x12\xde\x83\x0c\xef\xe2\xbe\x8fm\xc8" +
	"\x01D\x17\xce\x06(,!f\x051\x89\x7f\x88I\x00" +
	"\x88\xfbTN'1}\xc4h7\x89\xd1\x00\xc4J\xec" +
	"\x06(\xf4\x10\xb3\x9a\x18\xfdobt\x00\xb1\x0a\xe7\x02" +
	"\x14V\x10\xb3\x86\x18\xe3\x061\xb4\x81\x9cb\xfa\x88Y" +
	"GL\xf2:1I\x00\xb1V\xf5\xbc\x9a\x98\x0d\xc4\xa4" +
	"\xfe\"&\x05 \x06\x14\xb3\x86\x98!b\xd2\x7f\x12\x93" +
	"\x06\x10\x83\x8aYG\xcc02\xcc8vY6\xc7g" +
	"\xd4j;1\x09\x0c\x93\x80\x99Z\xa3*1\x139\x00" +
	"\x103\x80hc6\x120 f\x013\xb6m\x13\x1c" +
	"\x9a0\x80\xdb\x8b\xaav6\xf2F\x80\xf3r\x1d\xb3\xd1" +
	"\xcd1\x09:\x1ef\xa3\x1b\"\x00\x8dj\xcd\xc5ld" +
	"\xd8I\xd4\xab\xd0i\xa1\xd8'\xd1Z\xbd\x86\xd9H\xd4" +
	"\x01\x1a\x17D.\x97\xcb\xe5e\xa6X\x99&\xdd\xad\x91" +
	"t\xcdP\xbb#1\xed\xda\xa5\x92+=o\x1d\x18c" +
	"\xdbG1\x05\x0cS\x10\xa2\x1b\x80Wv\x87`\xec\xc0" +
	"\xa1\xe1|L\x81\xffQ\xbe$|\xb7\x94\x19nT%" +
	"e\xcf'1\x9a\x0f\xcf\xa6\xef2\xad\xc5\x00\xc8\xcc\x81" +
	"n\x00\xe4fn.\x00&\xcc\x95\xf4\xa3\x99]\x0b\x00" +
	"P7\x17\xd1\x8fa\xdeM?\xb6ZP\xb0\x0e^\xae" +
	"s\xc7\xa3\xc1\xd2\x18ih\xf1C\x1f\xdc\x98\x1b\\\x9b" +
	"o\x97\xc5\xff\xd7sN5\x8dSS\x1f\x88R\xf7N" +
	"\xce\xac\xa9\xb20\x1b\xfa\xab\xbd#\x15G}kG\x98" +
	"z\x85R\x7f\xe6XH`\xb4\x1a\x81\xb8\x1e O\x0a" +
	"\x9e\x17w\xea\x1c\xdc\x0aP\xb8\xb3\xe9T\x93\xf3\xa6O" +
	"w4\xddH.1\x13\x89\xc0\xa5\x03\x98o:\xa1D" +
	"\xb8\xa6\x05\x1e\xb5\x15\xfe\x08\xe1O\x12\xae\xeb\x81C\x1b" +
	"8\x02P\xa8\x13\xfe2\xe1\x86\x11\xf8\xf3\x88\xc2_ " +
	"\xfc]\xc2\x93\xc9\xc0\x9do+\xfc-\xc2'\x90\xe1^" +
	"W\x8d\xd5\xc3\xdb\x00\x878b6\xfa\x8f\x03$\xd0\xb7" +
	"\x07\x9c\x92\xacK\x8f.\xc3\xc9 \x1a\x93\xa2l[\xb1" +
	"`\xd4\xa57\x95T\x8b\x1dpJ\x90\x913\xb0\xe5z" +
	"P\x16p\x1a\xe5x\xb7\xa4\xaa5Wq\xc0\xa7W\xf4" +
	"*\xf6-\xb9Z\xbdvK.\xa6\x94\xc2C\xb9\x985" +
	"\xe6\x85\x0b\xff\xb0\x1b\xc0z\x9f\xa3u:f\xc5S\x04" +
	"~\xc0\xd1:\xcb\x10\x83e\x9bgz\x01\xac\x8f9Z" +
	"\x13\xb4\xe9\xe0F6\xcf\x91\\Ns\xb4.\xd0\x9a\x99" +
	"Z\xb3y\x9e\xb2\xcfr\xb4\xbe\xa4\x1ds\xb5c\xf3s" +
	"J\x9f\xe0h}E\x0bN\xa8\x05\x9b\x17)\xfd\x02G" +
	"\xeb[\x86\xed\xe5\xf8\xc5\xd8\xee\xc6\xdf\xfa=\xe9\x8e\xd9" +
	"\xe1M\xb9\xd7\x95\xdb\\\xe9\x8d6\xdf\xdb]Ys\x1b" +
	"\xcd\xb7~Y\xaf\x8e\xb92\x0c.\x8f9c\xe5]\xe5" +
	"i\x06\xc0j\xef\xf0\xe6\xe1\x99\xef\x8b\xdeI\x03u0" +
	"\xec\x7f\xdc\xde\xb9+\x1amK0\xda\x7f\x03\x00\x00\xff" +
	"\xff\xbe\x82\x16\xd1"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d8c6e9d1a4b2f307,
		Nodes: []uint64{
			0x8e0d32b60a612eb9,
			0x931072c4a18d0c61,
			0x9680f086587268f3,
			0x9e02a71670b20379,
			0xabf03d4c5c6a2ede,
			0xad3cf7360a023d1c,
			0xbe7ec061ddbdd224,
			0xe2cd6a34396bf6fa,
			0xe331a55c5a959108,
			0xf4dd868f57c8848a,
			0xfb6ecb8857844d67,
		},
		Compressed: true,
	})
}
