// Code generated by capnpc-go. DO NOT EDIT.

package replication

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type EventItem capnp.Struct

// EventItem_TypeID is the unique identifier for the type EventItem.
const EventItem_TypeID = 0xa560b6ae1894b3bc

func NewEventItem(s *capnp.Segment) (EventItem, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return EventItem(st), err
}

func NewRootEventItem(s *capnp.Segment) (EventItem, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return EventItem(st), err
}

func ReadRootEventItem(msg *capnp.Message) (EventItem, error) {
	root, err := msg.Root()
	return EventItem(root.Struct()), err
}

func (s EventItem) String() string {
	str, _ := text.Marshal(0xa560b6ae1894b3bc, capnp.Struct(s))
	return str
}

func (s EventItem) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventItem) DecodeFromPtr(p capnp.Ptr) EventItem {
	return EventItem(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventItem) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventItem) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventItem) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventItem) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventItem) Index() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EventItem) SetIndex(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EventItem) EventType() EventItem_EventType {
	return EventItem_EventType(capnp.Struct(s).Uint16(8))
}

func (s EventItem) SetEventType(v EventItem_EventType) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s EventItem) EventAction() EventItem_EventAction {
	return EventItem_EventAction(capnp.Struct(s).Uint16(10))
}

func (s EventItem) SetEventAction(v EventItem_EventAction) {
	capnp.Struct(s).SetUint16(10, uint16(v))
}

func (s EventItem) LastAffectIndex() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EventItem) SetLastAffectIndex(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s EventItem) Status() EventItem_Status {
	return EventItem_Status(capnp.Struct(s).Uint16(12))
}

func (s EventItem) SetStatus(v EventItem_Status) {
	capnp.Struct(s).SetUint16(12, uint16(v))
}

// EventItem_List is a list of EventItem.
type EventItem_List = capnp.StructList[EventItem]

// NewEventItem creates a new list of EventItem.
func NewEventItem_List(s *capnp.Segment, sz int32) (EventItem_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[EventItem](l), err
}

// EventItem_Future is a wrapper for a EventItem promised by a client call.
type EventItem_Future struct{ *capnp.Future }

func (f EventItem_Future) Struct() (EventItem, error) {
	p, err := f.Future.Ptr()
	return EventItem(p.Struct()), err
}

type EventItem_EventType uint16

// EventItem_EventType_TypeID is the unique identifier for the type EventItem_EventType.
const EventItem_EventType_TypeID = 0xa0e0e14592e0acfc

// Values of EventItem_EventType.
const (
	EventItem_EventType_dns  EventItem_EventType = 0
	EventItem_EventType_tls  EventItem_EventType = 1
	EventItem_EventType_http EventItem_EventType = 2
)

// String returns the enum's constant name.
func (c EventItem_EventType) String() string {
	switch c {
	case EventItem_EventType_dns:
		return "dns"
	case EventItem_EventType_tls:
		return "tls"
	case EventItem_EventType_http:
		return "http"

	default:
		return ""
	}
}

// EventItem_EventTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EventItem_EventTypeFromString(c string) EventItem_EventType {
	switch c {
	case "dns":
		return EventItem_EventType_dns
	case "tls":
		return EventItem_EventType_tls
	case "http":
		return EventItem_EventType_http

	default:
		return 0
	}
}

type EventItem_EventType_List = capnp.EnumList[EventItem_EventType]

func NewEventItem_EventType_List(s *capnp.Segment, sz int32) (EventItem_EventType_List, error) {
	return capnp.NewEnumList[EventItem_EventType](s, sz)
}

type EventItem_EventAction uint16

// EventItem_EventAction_TypeID is the unique identifier for the type EventItem_EventAction.
const EventItem_EventAction_TypeID = 0x8b8d9b50de73f832

// Values of EventItem_EventAction.
const (
	EventItem_EventAction_put EventItem_EventAction = 0
	EventItem_EventAction_del EventItem_EventAction = 1
)

// String returns the enum's constant name.
func (c EventItem_EventAction) String() string {
	switch c {
	case EventItem_EventAction_put:
		return "put"
	case EventItem_EventAction_del:
		return "del"

	default:
		return ""
	}
}

// EventItem_EventActionFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EventItem_EventActionFromString(c string) EventItem_EventAction {
	switch c {
	case "put":
		return EventItem_EventAction_put
	case "del":
		return EventItem_EventAction_del

	default:
		return 0
	}
}

type EventItem_EventAction_List = capnp.EnumList[EventItem_EventAction]

func NewEventItem_EventAction_List(s *capnp.Segment, sz int32) (EventItem_EventAction_List, error) {
	return capnp.NewEnumList[EventItem_EventAction](s, sz)
}

type EventItem_Status uint16

// EventItem_Status_TypeID is the unique identifier for the type EventItem_Status.
const EventItem_Status_TypeID = 0xceda55c195ff460d

// Values of EventItem_Status.
const (
	EventItem_Status_done    EventItem_Status = 0
	EventItem_Status_pending EventItem_Status = 1
)

// String returns the enum's constant name.
func (c EventItem_Status) String() string {
	switch c {
	case EventItem_Status_done:
		return "done"
	case EventItem_Status_pending:
		return "pending"

	default:
		return ""
	}
}

// EventItem_StatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EventItem_StatusFromString(c string) EventItem_Status {
	switch c {
	case "done":
		return EventItem_Status_done
	case "pending":
		return EventItem_Status_pending

	default:
		return 0
	}
}

type EventItem_Status_List = capnp.EnumList[EventItem_Status]

func NewEventItem_Status_List(s *capnp.Segment, sz int32) (EventItem_Status_List, error) {
	return capnp.NewEnumList[EventItem_Status](s, sz)
}

type EventLog capnp.Struct

// EventLog_TypeID is the unique identifier for the type EventLog.
const EventLog_TypeID = 0xa9daaf59f32abbe5

func NewEventLog(s *capnp.Segment) (EventLog, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return EventLog(st), err
}

func NewRootEventLog(s *capnp.Segment) (EventLog, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return EventLog(st), err
}

func ReadRootEventLog(msg *capnp.Message) (EventLog, error) {
	root, err := msg.Root()
	return EventLog(root.Struct()), err
}

func (s EventLog) String() string {
	str, _ := text.Marshal(0xa9daaf59f32abbe5, capnp.Struct(s))
	return str
}

func (s EventLog) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventLog) DecodeFromPtr(p capnp.Ptr) EventLog {
	return EventLog(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventLog) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventLog) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventLog) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventLog) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventLog) Items() (EventItem_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EventItem_List(p.List()), err
}

func (s EventLog) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EventLog) SetItems(v EventItem_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated EventItem_List, preferring placement in s's segment.
func (s EventLog) NewItems(n int32) (EventItem_List, error) {
	l, err := NewEventItem_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return EventItem_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s EventLog) Total() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EventLog) SetTotal(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EventLog) StartTime() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EventLog) SetStartTime(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EventLog) CloseTime() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EventLog) SetCloseTime(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// EventLog_List is a list of EventLog.
type EventLog_List = capnp.StructList[EventLog]

// NewEventLog creates a new list of EventLog.
func NewEventLog_List(s *capnp.Segment, sz int32) (EventLog_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[EventLog](l), err
}

// EventLog_Future is a wrapper for a EventLog promised by a client call.
type EventLog_Future struct{ *capnp.Future }

func (f EventLog_Future) Struct() (EventLog, error) {
	p, err := f.Future.Ptr()
	return EventLog(p.Struct()), err
}

const schema_c4f4d6e1d8b1a271 = "x\xda\x94\x92OH\x15_\x14\xc7\xcfw\xee<\xe7'" +
	"\xf8~\xe3e\x9e\x90\x0by m\x12\xd2\xf2-\x047" +
	"\xa6``\x04y\xcd\x16A\x8b\xc6\xf7\xae60\xceL" +
	"o\xee+\x85\xa2\x92\x16I\x09\x15\xb6\xe8\xcf\xc2\x02\x17" +
	"E\x14\x11\xb5\xa9M\xd0\xa6M\xcb\x08\x17\xa1\x8bh\x1d" +
	"\xb5h\x11L\xdc\xf7w\xd0E\xb6\x9a\xe1\x9c3\x9f9" +
	"\xe7s\xce\x81\x09\x1c2\x0ff\xf3\x8c\x0c\xb17\xd3\x96" +
	"\x0c\xfe\x8a\xbfL\xde_\xb9N|\x9f\x91\xbc}\xb9\xba" +
	"\xe7\xd9\xeb\xd3\xebD(T\xf0\x04\xce\x0a,\"g\x19" +
	"C\x84\xe4\xf7\xd3\xcd\xdb\xe3[\x9bk;*Wp\x0f" +
	"\xcez\xb5\xf2!\x8e\x11ZI\x91\x07K\xce>z\xf1" +
	"y\xeb\xd3\xcf\xf7dZD\x85W8\x02\xe7\x03\x86\x88" +
	"\x0a\xdf\x91\x07!\xf9\xfa\xa6\xef\xc7\xc9\xe7\x1b\x8f\xb7U" +
	"g4\xb0\x90ecpz\x98fw\xb3o\x84${" +
	"8\xb9\xf3\xee\xc4\xc6\xc7\x1d]d\xcc%8\xdd\xfa\x1f" +
	"N\x979D\xfb\x930\x92eW\x85\xe5\xcc@YF" +
	"\xbeWt\x95\x17\x06\x03\xe7]\xbf\xbf\xe8FA4<" +
	"~N\x06jB\xc9\xf9\xfe\xea\xdbh\xd1\xd6\x05\x93\x80" +
	"\xf8\x0f\x06\x11\xe7\xbdD\x00o\xef%\xb2\xa2\x8a\xb2J" +
	"\xd2\xffW\xe6\xf4\"\x8b\xa4&vT\x89=5b\x97" +
	"~\x18<\xdbGd\x95\x82\xd8R~l\x9fQ*j" +
	"\xd2\xcd\xbf\xd1\x89D\x07\xd2\x1b\xe1S\xa9E\xf2\x99\x94" +
	"%>\x9c\xd4[\x89\x082\xa9\x8f\xaa\xc8\xf2\xc2`\xe4" +
	"\xb8rU%\x169f\x12\x99 \xe2\x17\x07\x89\xc4\x02" +
	"\x83\xb8j\x80\xc3\xccA\x07\xafL\x11\x89\xcb\x0c\xe2\x86" +
	"\x01ndr\xd5Y\x96g\x88\xc45\x06\xb1j\x803" +
	"#\x07F\xc4o-\x11\x89\x9b\x0c\xe2\x81\x01n\xb6\xe5" +
	"`\x12\xf1\xbb\xc3Db\x95A\xac\x19\xc8{AI." +
	"\xa0\x9d\x0c\xb4\x13\x12\xd9\xea\x0cvk\x1c\x02\xecF\xb6" +
	"\xd1+\xec\xd6\x84\xf5\xbc\xef\xc6jtvV\xa2\xa8&" +
	"4\x96\x1a\xdc\x91\xb8:\x17\xec\x96\x87\xfa'\xbb2|" +
	"4\x9c#\xbd\xb4\xce\xa6\x16Wk9\xc5 \x16\x0c\x00" +
	"5+\x15\x1d\x8b\x18\xc4\x05m\x055+\x8bS)\x7f" +
	"\x0d+i\x7fyO\xc9\xf9\x18\xff\x13&\x19\xd0\x99\xbe" +
	"`\x1d\xcc\xabP\xb9~\xd3O\xac\xdc\xb2\x9a\xf6\xe6\xb5" +
	"\x9fF\xac\xe8\x87\xb1\xdc\x16\xdb\xfdY\xd66N\xa9+" +
	"\xef\xab]\xf9\x18\x91]\x0a\x03y)\x92A\xc9\x0b\xe6" +
	"\xfe\x04\x00\x00\xff\xff\x8c\xab1\xdc"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c4f4d6e1d8b1a271,
		Nodes: []uint64{
			0x8b8d9b50de73f832,
			0xa0e0e14592e0acfc,
			0xa560b6ae1894b3bc,
			0xa9daaf59f32abbe5,
			0xceda55c195ff460d,
		},
		Compressed: true,
	})
}
