// Code generated by capnpc-go. DO NOT EDIT.

package replication

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type EventItem capnp.Struct

// EventItem_TypeID is the unique identifier for the type EventItem.
const EventItem_TypeID = 0xa560b6ae1894b3bc

func NewEventItem(s *capnp.Segment) (EventItem, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return EventItem(st), err
}

func NewRootEventItem(s *capnp.Segment) (EventItem, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return EventItem(st), err
}

func ReadRootEventItem(msg *capnp.Message) (EventItem, error) {
	root, err := msg.Root()
	return EventItem(root.Struct()), err
}

func (s EventItem) String() string {
	str, _ := text.Marshal(0xa560b6ae1894b3bc, capnp.Struct(s))
	return str
}

func (s EventItem) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventItem) DecodeFromPtr(p capnp.Ptr) EventItem {
	return EventItem(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventItem) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventItem) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventItem) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventItem) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventItem) Index() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EventItem) SetIndex(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EventItem) EventType() EventItem_EventType {
	return EventItem_EventType(capnp.Struct(s).Uint16(8))
}

func (s EventItem) SetEventType(v EventItem_EventType) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s EventItem) EventKey() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EventItem) HasEventKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EventItem) EventKeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EventItem) SetEventKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EventItem) EventAction() EventItem_EventAction {
	return EventItem_EventAction(capnp.Struct(s).Uint16(10))
}

func (s EventItem) SetEventAction(v EventItem_EventAction) {
	capnp.Struct(s).SetUint16(10, uint16(v))
}

func (s EventItem) LastAffectIndex() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EventItem) SetLastAffectIndex(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s EventItem) Status() EventItem_Status {
	return EventItem_Status(capnp.Struct(s).Uint16(12))
}

func (s EventItem) SetStatus(v EventItem_Status) {
	capnp.Struct(s).SetUint16(12, uint16(v))
}

// EventItem_List is a list of EventItem.
type EventItem_List = capnp.StructList[EventItem]

// NewEventItem creates a new list of EventItem.
func NewEventItem_List(s *capnp.Segment, sz int32) (EventItem_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[EventItem](l), err
}

// EventItem_Future is a wrapper for a EventItem promised by a client call.
type EventItem_Future struct{ *capnp.Future }

func (f EventItem_Future) Struct() (EventItem, error) {
	p, err := f.Future.Ptr()
	return EventItem(p.Struct()), err
}

type EventItem_EventType uint16

// EventItem_EventType_TypeID is the unique identifier for the type EventItem_EventType.
const EventItem_EventType_TypeID = 0xa0e0e14592e0acfc

// Values of EventItem_EventType.
const (
	EventItem_EventType_dns  EventItem_EventType = 0
	EventItem_EventType_tls  EventItem_EventType = 1
	EventItem_EventType_http EventItem_EventType = 2
)

// String returns the enum's constant name.
func (c EventItem_EventType) String() string {
	switch c {
	case EventItem_EventType_dns:
		return "dns"
	case EventItem_EventType_tls:
		return "tls"
	case EventItem_EventType_http:
		return "http"

	default:
		return ""
	}
}

// EventItem_EventTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EventItem_EventTypeFromString(c string) EventItem_EventType {
	switch c {
	case "dns":
		return EventItem_EventType_dns
	case "tls":
		return EventItem_EventType_tls
	case "http":
		return EventItem_EventType_http

	default:
		return 0
	}
}

type EventItem_EventType_List = capnp.EnumList[EventItem_EventType]

func NewEventItem_EventType_List(s *capnp.Segment, sz int32) (EventItem_EventType_List, error) {
	return capnp.NewEnumList[EventItem_EventType](s, sz)
}

type EventItem_EventAction uint16

// EventItem_EventAction_TypeID is the unique identifier for the type EventItem_EventAction.
const EventItem_EventAction_TypeID = 0x8b8d9b50de73f832

// Values of EventItem_EventAction.
const (
	EventItem_EventAction_put EventItem_EventAction = 0
	EventItem_EventAction_del EventItem_EventAction = 1
)

// String returns the enum's constant name.
func (c EventItem_EventAction) String() string {
	switch c {
	case EventItem_EventAction_put:
		return "put"
	case EventItem_EventAction_del:
		return "del"

	default:
		return ""
	}
}

// EventItem_EventActionFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EventItem_EventActionFromString(c string) EventItem_EventAction {
	switch c {
	case "put":
		return EventItem_EventAction_put
	case "del":
		return EventItem_EventAction_del

	default:
		return 0
	}
}

type EventItem_EventAction_List = capnp.EnumList[EventItem_EventAction]

func NewEventItem_EventAction_List(s *capnp.Segment, sz int32) (EventItem_EventAction_List, error) {
	return capnp.NewEnumList[EventItem_EventAction](s, sz)
}

type EventItem_Status uint16

// EventItem_Status_TypeID is the unique identifier for the type EventItem_Status.
const EventItem_Status_TypeID = 0xceda55c195ff460d

// Values of EventItem_Status.
const (
	EventItem_Status_overlaped EventItem_Status = 0
	EventItem_Status_ontop     EventItem_Status = 1
)

// String returns the enum's constant name.
func (c EventItem_Status) String() string {
	switch c {
	case EventItem_Status_overlaped:
		return "overlaped"
	case EventItem_Status_ontop:
		return "ontop"

	default:
		return ""
	}
}

// EventItem_StatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EventItem_StatusFromString(c string) EventItem_Status {
	switch c {
	case "overlaped":
		return EventItem_Status_overlaped
	case "ontop":
		return EventItem_Status_ontop

	default:
		return 0
	}
}

type EventItem_Status_List = capnp.EnumList[EventItem_Status]

func NewEventItem_Status_List(s *capnp.Segment, sz int32) (EventItem_Status_List, error) {
	return capnp.NewEnumList[EventItem_Status](s, sz)
}

type EventLog capnp.Struct

// EventLog_TypeID is the unique identifier for the type EventLog.
const EventLog_TypeID = 0xa9daaf59f32abbe5

func NewEventLog(s *capnp.Segment) (EventLog, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 1})
	return EventLog(st), err
}

func NewRootEventLog(s *capnp.Segment) (EventLog, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 1})
	return EventLog(st), err
}

func ReadRootEventLog(msg *capnp.Message) (EventLog, error) {
	root, err := msg.Root()
	return EventLog(root.Struct()), err
}

func (s EventLog) String() string {
	str, _ := text.Marshal(0xa9daaf59f32abbe5, capnp.Struct(s))
	return str
}

func (s EventLog) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EventLog) DecodeFromPtr(p capnp.Ptr) EventLog {
	return EventLog(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EventLog) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EventLog) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EventLog) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EventLog) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EventLog) Items() (EventItem_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EventItem_List(p.List()), err
}

func (s EventLog) HasItems() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EventLog) SetItems(v EventItem_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewItems sets the items field to a newly
// allocated EventItem_List, preferring placement in s's segment.
func (s EventLog) NewItems(n int32) (EventItem_List, error) {
	l, err := NewEventItem_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return EventItem_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s EventLog) Total() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EventLog) SetTotal(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EventLog) NotOverlap() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EventLog) SetNotOverlap(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EventLog) StartTime() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EventLog) SetStartTime(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s EventLog) CloseTime() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s EventLog) SetCloseTime(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

// EventLog_List is a list of EventLog.
type EventLog_List = capnp.StructList[EventLog]

// NewEventLog creates a new list of EventLog.
func NewEventLog_List(s *capnp.Segment, sz int32) (EventLog_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 1}, sz)
	return capnp.StructList[EventLog](l), err
}

// EventLog_Future is a wrapper for a EventLog promised by a client call.
type EventLog_Future struct{ *capnp.Future }

func (f EventLog_Future) Struct() (EventLog, error) {
	p, err := f.Future.Ptr()
	return EventLog(p.Struct()), err
}

const schema_c4f4d6e1d8b1a271 = "x\xda\x94\x93\xcfKT]\x18\xc7\x9f\xef9w\x9cW" +
	"\x98y\xe7=\xcc\xbc\xe0&\x06\xa4MBZ\xba\x10\xdc" +
	"\x98\x81\x81V\xe8\x99\x8c0\x08\xba\xce\x1ck\xe2z\xef" +
	"m\xee\xd1t\xd1Fh\x11\xe5\xa2P\xc8~\x80E\x03" +
	"\x15\xf6\x8b2\x84\x0a\x0a\xdc\xb4i\x19\xe1\"t\xd1\x1f" +
	"\x10\xb5h\x11\xdc8\xf3\x1b]d\xab\xb9|\xcf\xf7|" +
	"\xcf\xf3|\x9eg\xf6\x9d\xc3\x01k\x7f<\xcd\x89\xc9\xdd" +
	"\x91\xa6\xb0\xf3g\xf0e\xf8\xd6\xdc\x15\x12{X\xf8\xe6" +
	"\xc5|\xcb\x93W\xa7\x8bD\xe8\x9a\xc4#$\xe7\x10%" +
	"J^F7!\xfc\xb5\xbcq\xbd\x7fsci\x9bs" +
	"\x0e7\x91,\x96\x9cw1D\xa8\x1f\xca4xx\xfe" +
	"\xde\xf3\xcf\x9b\x9f~\xacQ\xc4X\xbaV0\x88\xe4\x07" +
	"t\x13u}\xc3\x09\x10\xc2\xaf\xaf\xdb\xbe\x8f>]\x7f" +
	"h\xec\xd6V\xfbQ~\x10\xc9S\xdc|\x8e\xf2\xb4\xb1" +
	"\xc7\x0f\x85\x0b\xef\x8f\xaf\x7f\xdcV\xc7%k\x16\xc9E" +
	"\xcb\xd4\xb1`u\xd3\xde\xd0\xf3U\xc1\xd6^!\xd2Q" +
	"P\xbe\x93\xcf\xda:\xef\xb9\x1d\x17l\xa7=k\xfb\xae" +
	"\xdf\xd3?\xa5\\=\xa0\xd5D{\xe9\xab/\x9b0\x86" +
	"a@\xfe\x03F$D+\x11 \x9a[\x89\xa2\xfe\xa4" +
	"\x8e\xe6\x94\xf3\xb7\x99#3\xdcW&1VJ\xdcU" +
	"N\xfc\xdf\xfc0\x11o#\x8a\xe6\xdc \xaa\x9d q" +
	"Vk\xbf\x96n\xfd)\x9dH\xc6\xd08\x13\x91i\x18" +
	"\xa5\x18k\xa0$z\xc2J)>A\x85\x95V5E" +
	"\xf3\x9e\xdb{L\xdbz2\x90-\xdc\"\xb2@$\x16" +
	";\x89\xe4<\x87\\b\x10\xb0R0\xe2\x9d\x0c\x91\xbc" +
	"\xcd!\x1f0\x80\xa5J\xad\x14\x07\x89\xe4}\x0e\xf9\x8c" +
	"A\xf0H\x0a\x9cH<\x1e#\x92\xcb\x1cr\x95AX" +
	",\x05\x8bH\xac\xcc\x12\xc9\x97\x1c\xf2\x1d\x83\x884\xa5" +
	"\x10!\x12o{\x88\xe4*\x87\\cH\xe7\xdd\x9c\x9a" +
	"F314\x13BU\xaf\x16\x89z\x8b\x04$\xaa\xa7" +
	"\x87\xd5\x0c\x11!F\x0c\xb1\xaaV\xed\x09\x89:\x89\xca" +
	"\x1d\xc7\x0et\xdf\xf8\xb8BV\x0f\x98\xa7\xa8\xfaVo" +
	"P\xea\x1f\x89:\xaf\xca\x95\x1dM\xe2\x88w\x86\xccp" +
	"S5|\x17\x0d\xbei\x0e9\xcf\x00\x94\xe9]3\xda" +
	"U\x0ey\x83A0\x94\xf1-\x9cl\xe0\xccY\x19_" +
	"#ga\xf12\xbeb\xa6\x0e:\x9d\xd7j\"\xc0\xbf" +
	"\x84a\x0e\xfc\xd7\xb8\xfeFLkO\xdbN\x0d\xa4\xeb" +
	"\xe9\xa1)Up\x88\xdb~M\x0c\xb4]\xd0#\xf9\x09" +
	"C\xb7\xaae\x1d/P[\xb4\x9d/zy\x87\xa8\xe1" +
	"\x7f\x93)my\xbc\x93(\xf4L\x01\xb6\xaf\x08\xb9\xb4" +
	"\xe7j\xcf\xff\x1d\x00\x00\xff\xff\xc1kI."

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c4f4d6e1d8b1a271,
		Nodes: []uint64{
			0x8b8d9b50de73f832,
			0xa0e0e14592e0acfc,
			0xa560b6ae1894b3bc,
			0xa9daaf59f32abbe5,
			0xceda55c195ff460d,
		},
		Compressed: true,
	})
}
